C:/Dev/Techstorm-v5/src/application/prototyping/ChunkTesting.h File Reference
#include <raylib.h>
#include <raymath.h>
#include <cmath>
#include <iostream>
#include <FastNoiseLite.h>
#include <vector>
#include "rlights.h"
#include <rlgl.h>
#include <external/glad.h>
Classes
struct Vec3
struct Chunk
Macros
#define RLIGHTS_IMPLEMENTATION
#define GLSL_VERSION 100
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 450
#define CHUNK_SIZE 32
#define VIEW_DISTANCE 8
Functions
Vector3 getVertex (const std::vector< float > &data, size_t index)
Vector3 getNormal (const std::vector< float > &data, size_t index)
Vector2 getTexcoord (const std::vector< float > &data, size_t index)
void generateMeshData (const std::vector< float > &vertexData, std::vector< unsigned short > &indices, std::vector< float > &normals, std::vector< float > &texCoords)
float * fromVec3 (const Vec3 &v)
Mesh loadMeshes (Vector3 *vertices, Vector3 *normals, Vector2 *texcoords, int numVertices, int *indices, int numTriangles)
void GenerateTerrain ()
void DrawTerrain ()
int ChunkTesting ()
Variables
Shader shader
Chunk chunks [VIEW_DISTANCE *2+1][VIEW_DISTANCE *2+1]
Camera camera
Macro Definition Documentation
CHUNK_SIZE
#define CHUNK_SIZE 32
Definition at line 20 of file ChunkTesting.h.
GLSL_VERSION
#define GLSL_VERSION 100
Definition at line 15 of file ChunkTesting.h.
RLIGHTS_IMPLEMENTATION
#define RLIGHTS_IMPLEMENTATION
Definition at line 8 of file ChunkTesting.h.
SCREEN_HEIGHT
#define SCREEN_HEIGHT 450
Definition at line 18 of file ChunkTesting.h.
SCREEN_WIDTH
#define SCREEN_WIDTH 800
Definition at line 17 of file ChunkTesting.h.
VIEW_DISTANCE
#define VIEW_DISTANCE 8
Definition at line 21 of file ChunkTesting.h.
Function Documentation
ChunkTesting()
int ChunkTesting ()
Definition at line 304 of file ChunkTesting.h.
References camera, GLSL_VERSION, InitWindow(), and shader.
DrawTerrain()
void DrawTerrain ()
Definition at line 233 of file ChunkTesting.h.
References camera, CHUNK_SIZE, chunks, Chunk::heightMap, Chunk::position, and VIEW_DISTANCE.
fromVec3()
float * fromVec3 (const Vec3 & v)
Definition at line 110 of file ChunkTesting.h.
generateMeshData()
void generateMeshData (const std::vector< float > & vertexData, std::vector< unsigned short > & indices, std::vector< float > & normals, std::vector< float > & texCoords)
Definition at line 71 of file ChunkTesting.h.
References Vec3::cross(), getVertex(), Vec3::normalize(), Vec3::x, Vec3::y, and Vec3::z.
Referenced by Chunk::generateMesh().
GenerateTerrain()
void GenerateTerrain ()
Definition at line 171 of file ChunkTesting.h.
References CHUNK_SIZE, chunks, Chunk::heightMap, Chunk::position, and VIEW_DISTANCE.
getNormal()
Vector3 getNormal (const std::vector< float > & data, size_t index)
Definition at line 63 of file ChunkTesting.h.
References getVertex().
getTexcoord()
Vector2 getTexcoord (const std::vector< float > & data, size_t index)
Definition at line 67 of file ChunkTesting.h.
getVertex()
Vector3 getVertex (const std::vector< float > & data, size_t index)
Definition at line 59 of file ChunkTesting.h.
Referenced by generateMeshData(), and getNormal().
loadMeshes()
Mesh loadMeshes (Vector3 * vertices, Vector3 * normals, Vector2 * texcoords, int numVertices, int * indices, int numTriangles)
Definition at line 156 of file ChunkTesting.h.
References Chunk::vertices.
Variable Documentation
camera
Camera camera
Definition at line 232 of file ChunkTesting.h.
Referenced by ChunkTesting(), DrawTerrain(), and PrototypePhysicsTerrain().
chunks
Chunk chunks[VIEW_DISTANCE *2+1][VIEW_DISTANCE *2+1]
Definition at line 154 of file ChunkTesting.h.
Referenced by DrawTerrain(), GenerateTerrain(), Terrain::Terrain(), and Terrain::texture().
shader
Shader shader
Definition at line 23 of file ChunkTesting.h.
Referenced by ChunkTesting(), and PrototypePhysicsTerrain().