C:/Dev/Techstorm-v5/src/application/prototyping/PrototypingTerrain.h File Reference
#include <raylib.h>
#include <raymath.h>
#include <cmath>
#include <iostream>
#include <FastNoiseLite.h>
#include <vector>
#include "rlights.h"
Classes
struct Chunk
Macros
#define RLIGHTS_IMPLEMENTATION
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 450
#define CHUNK_SIZE 32
#define VIEW_DISTANCE 8
Functions
Mesh loadMeshes (Vector3 *vertices, Vector3 *normals, Vector2 *texcoords, int numVertices, int *indices, int numTriangles)
Mesh genMeshFromChunk (const Chunk &chunk)
void GenerateTerrain ()
void DrawTerrain ()
int PrototypeTerrain ()
Variables
Shader shader
Chunk chunks [VIEW_DISTANCE *2+1][VIEW_DISTANCE *2+1]
Camera camera
Macro Definition Documentation
CHUNK_SIZE
#define CHUNK_SIZE 32
Definition at line 14 of file PrototypingTerrain.h.
RLIGHTS_IMPLEMENTATION
#define RLIGHTS_IMPLEMENTATION
Definition at line 8 of file PrototypingTerrain.h.
SCREEN_HEIGHT
#define SCREEN_HEIGHT 450
Definition at line 12 of file PrototypingTerrain.h.
SCREEN_WIDTH
#define SCREEN_WIDTH 800
Definition at line 11 of file PrototypingTerrain.h.
VIEW_DISTANCE
#define VIEW_DISTANCE 8
Definition at line 15 of file PrototypingTerrain.h.
Function Documentation
DrawTerrain()
void DrawTerrain ()
Definition at line 187 of file PrototypingTerrain.h.
References camera, CHUNK_SIZE, chunks, Chunk::heightMap, Chunk::position, and VIEW_DISTANCE.
Referenced by PrototypeTerrain().
GenerateTerrain()
void GenerateTerrain ()
Definition at line 125 of file PrototypingTerrain.h.
References CHUNK_SIZE, chunks, Chunk::heightMap, Chunk::position, and VIEW_DISTANCE.
Referenced by PrototypeTerrain().
genMeshFromChunk()
Mesh genMeshFromChunk (const Chunk & chunk)
Definition at line 42 of file PrototypingTerrain.h.
References CHUNK_SIZE, Chunk::heightMap, loadMeshes(), and Chunk::position.
loadMeshes()
Mesh loadMeshes (Vector3 * vertices, Vector3 * normals, Vector2 * texcoords, int numVertices, int * indices, int numTriangles)
Definition at line 27 of file PrototypingTerrain.h.
References Chunk::vertices.
Referenced by genMeshFromChunk().
PrototypeTerrain()
int PrototypeTerrain ()
Definition at line 235 of file PrototypingTerrain.h.
References camera, DrawTerrain(), GenerateTerrain(), SCREEN_HEIGHT, SCREEN_WIDTH, and shader.
Variable Documentation
camera
Camera camera
Definition at line 186 of file PrototypingTerrain.h.
Referenced by DrawTerrain(), and PrototypeTerrain().
chunks
Chunk chunks[VIEW_DISTANCE *2+1][VIEW_DISTANCE *2+1]
Definition at line 25 of file PrototypingTerrain.h.
Referenced by DrawTerrain(), and GenerateTerrain().
shader
Shader shader
Definition at line 17 of file PrototypingTerrain.h.
Referenced by PrototypeTerrain().