Techstorm::ScriptingAPI Class Reference
Everything related to the scripting API, i.e loading/unloading libraries, registering functions, etc. As is mentioned at the file's documentation, only lua is supported at the moment.
#include <ScriptingAPI.h>
Public Member Functions
ScriptingAPI ()=default
int InitializeScripting (LuaLibraryRegistry const &libraries, LuaFunctionRegistry const &functions)
Initializes the scripting API.
int RegisterLua ()
Registers the scripting API for Lua.
int RegisterAngelScript ()
Registers the scripting API for AngelScript. This is just for organization sake and it could be merged with the lua version, but it wont be.
Public Attributes
sol::state mLua
Additional Inherited Members
Static Public Member Functions inherited from Techstorm::Singleton< ScriptingAPI >
static ScriptingAPI & Instance ()
Retrieves the current singleton instance as a reference.
Detailed Description
Everything related to the scripting API, i.e loading/unloading libraries, registering functions, etc. As is mentioned at the file's documentation, only lua is supported at the moment.
See also
Singleton<ScriptingAPI>
Definition at line 48 of file ScriptingAPI.h.
Constructor & Destructor Documentation
ScriptingAPI()
Techstorm::ScriptingAPI::ScriptingAPI () [default]
Member Function Documentation
InitializeScripting()
int Techstorm::ScriptingAPI::InitializeScripting (LuaLibraryRegistry const & libraries, LuaFunctionRegistry const & functions)
Initializes the scripting API.
Returns
an integer value that represents the result of the operation.
Definition at line 7 of file ScriptingAPI.cpp.
Referenced by main().
RegisterAngelScript()
int Techstorm::ScriptingAPI::RegisterAngelScript ()
Registers the scripting API for AngelScript. This is just for organization sake and it could be merged with the lua version, but it wont be.
Returns
an integer value that represents the result of the operation.
Definition at line 36 of file ScriptingAPI.cpp.
RegisterLua()
int Techstorm::ScriptingAPI::RegisterLua ()
Registers the scripting API for Lua.
Returns
an integer value that represents the result of the operation.
Definition at line 20 of file ScriptingAPI.cpp.
References Techstorm::GetConfigString().
Referenced by main().
Member Data Documentation
mLua
sol::state Techstorm::ScriptingAPI::mLua
Definition at line 69 of file ScriptingAPI.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/modding/ScriptingAPI.h
C:/Dev/Techstorm-v5/src/engine/modding/ScriptingAPI.cpp