RenderInterface_BackwardCompatible_GL3 Class Reference
#include <RmlUi_Renderer_BackwardCompatible_GL3.h>
Public Member Functions
RenderInterface_BackwardCompatible_GL3 ()
~RenderInterface_BackwardCompatible_GL3 ()
operator bool () const
void SetViewport (int viewport_width, int viewport_height)
void BeginFrame ()
void EndFrame ()
void Clear ()
void RenderGeometry (Rml::Vertex *vertices, int num_vertices, int *indices, int num_indices, Rml::TextureHandle texture, const Rml::Vector2f &translation) override
Rml::CompiledGeometryHandle CompileGeometry (Rml::Vertex *vertices, int num_vertices, int *indices, int num_indices, Rml::TextureHandle texture) override
void RenderCompiledGeometry (Rml::CompiledGeometryHandle geometry, const Rml::Vector2f &translation) override
void ReleaseCompiledGeometry (Rml::CompiledGeometryHandle geometry) override
void EnableScissorRegion (bool enable) override
void SetScissorRegion (int x, int y, int width, int height) override
bool LoadTexture (Rml::TextureHandle &texture_handle, Rml::Vector2i &texture_dimensions, const Rml::String &source) override
bool GenerateTexture (Rml::TextureHandle &texture_handle, const Rml::byte *source, const Rml::Vector2i &source_dimensions) override
void ReleaseTexture (Rml::TextureHandle texture_handle) override
void SetTransform (const Rml::Matrix4f *transform) override
Static Public Attributes
static const Rml::TextureHandle TextureEnableWithoutBinding = Rml::TextureHandle(-1)
Detailed Description
Definition at line 45 of file RmlUi_Renderer_BackwardCompatible_GL3.h.
Constructor & Destructor Documentation
RenderInterface_BackwardCompatible_GL3()
RenderInterface_BackwardCompatible_GL3::RenderInterface_BackwardCompatible_GL3 ()
Definition at line 318 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
~RenderInterface_BackwardCompatible_GL3()
RenderInterface_BackwardCompatible_GL3::~RenderInterface_BackwardCompatible_GL3 ()
Definition at line 326 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
Member Function Documentation
BeginFrame()
void RenderInterface_BackwardCompatible_GL3::BeginFrame ()
Definition at line 338 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References GL_ALWAYS, GL_BLEND, GL_BLEND_DST_ALPHA, GL_BLEND_DST_RGB, GL_BLEND_EQUATION_ALPHA, GL_BLEND_EQUATION_RGB, GL_BLEND_SRC_ALPHA, GL_BLEND_SRC_RGB, GL_COLOR_CLEAR_VALUE, GL_CULL_FACE, GL_FUNC_ADD, GL_KEEP, GL_ONE_MINUS_SRC_ALPHA, GL_SCISSOR_BOX, GL_SCISSOR_TEST, GL_SRC_ALPHA, GL_STENCIL_BACK_FAIL, GL_STENCIL_BACK_FUNC, GL_STENCIL_BACK_PASS_DEPTH_FAIL, GL_STENCIL_BACK_PASS_DEPTH_PASS, GL_STENCIL_BACK_REF, GL_STENCIL_BACK_VALUE_MASK, GL_STENCIL_BACK_WRITEMASK, GL_STENCIL_CLEAR_VALUE, GL_STENCIL_FAIL, GL_STENCIL_FUNC, GL_STENCIL_PASS_DEPTH_FAIL, GL_STENCIL_PASS_DEPTH_PASS, GL_STENCIL_REF, GL_STENCIL_TEST, GL_STENCIL_VALUE_MASK, GL_STENCIL_WRITEMASK, GL_VIEWPORT, glBlendEquation, glBlendFunc, glClearColor, glClearStencil, glDisable, glEnable, glGetFloatv, glGetIntegerv, glIsEnabled, glStencilFunc, glStencilMask, glStencilOp, glViewport, and SetTransform().
Clear()
void RenderInterface_BackwardCompatible_GL3::Clear ()
Definition at line 442 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References GL_COLOR_BUFFER_BIT, GL_STENCIL_BUFFER_BIT, glClear, glClearColor, and glClearStencil.
CompileGeometry()
Rml::CompiledGeometryHandle RenderInterface_BackwardCompatible_GL3::CompileGeometry (Rml::Vertex * vertices, int num_vertices, int * indices, int num_indices, Rml::TextureHandle texture) [override]
Definition at line 461 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References Gfx::Color0, Gfx::CompiledGeometryData::draw_count, GL_ARRAY_BUFFER, GL_ELEMENT_ARRAY_BUFFER, GL_FALSE, GL_FLOAT, GL_STATIC_DRAW, GL_TRUE, GL_UNSIGNED_BYTE, glBindBuffer, glBindVertexArray, glBufferData, glEnableVertexAttribArray, glGenBuffers, glGenVertexArrays, glVertexAttribPointer, Gfx::CompiledGeometryData::ibo, Gfx::Position, Gfx::TexCoord0, Gfx::CompiledGeometryData::texture, Gfx::CompiledGeometryData::vao, and Gfx::CompiledGeometryData::vbo.
Referenced by RenderGeometry().
EnableScissorRegion()
void RenderInterface_BackwardCompatible_GL3::EnableScissorRegion (bool enable) [override]
Definition at line 549 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References GL_ALWAYS, GL_EQUAL, GL_SCISSOR_TEST, glDisable, glEnable, and glStencilFunc.
EndFrame()
void RenderInterface_BackwardCompatible_GL3::EndFrame ()
Definition at line 398 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References GL_BACK, GL_BLEND, GL_CULL_FACE, GL_FRONT, GL_SCISSOR_TEST, GL_STENCIL_TEST, glBlendEquationSeparate, glBlendFuncSeparate, glClearColor, glClearStencil, glDisable, glEnable, glScissor, glStencilFuncSeparate, glStencilMaskSeparate, glStencilOpSeparate, and glViewport.
GenerateTexture()
bool RenderInterface_BackwardCompatible_GL3::GenerateTexture (Rml::TextureHandle & texture_handle, const Rml::byte * source, const Rml::Vector2i & source_dimensions) [override]
Definition at line 718 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References GL_LINEAR, GL_REPEAT, GL_RGBA, GL_RGBA8, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNSIGNED_BYTE, glBindTexture, glGenTextures, glTexImage2D, and glTexParameteri.
Referenced by LoadTexture().
LoadTexture()
bool RenderInterface_BackwardCompatible_GL3::LoadTexture (Rml::TextureHandle & texture_handle, Rml::Vector2i & texture_dimensions, const Rml::String & source) [override]
Definition at line 627 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References TGAHeader::bitsPerPixel, TGAHeader::dataType, GenerateTexture(), TGAHeader::height, TGAHeader::imageDescriptor, and TGAHeader::width.
operator bool()
RenderInterface_BackwardCompatible_GL3::operator bool () const [inline], [explicit]
Definition at line 51 of file RmlUi_Renderer_BackwardCompatible_GL3.h.
ReleaseCompiledGeometry()
void RenderInterface_BackwardCompatible_GL3::ReleaseCompiledGeometry (Rml::CompiledGeometryHandle geometry) [override]
Definition at line 538 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References glDeleteBuffers, glDeleteVertexArrays, Gfx::CompiledGeometryData::ibo, Gfx::CompiledGeometryData::vao, and Gfx::CompiledGeometryData::vbo.
Referenced by RenderGeometry().
ReleaseTexture()
void RenderInterface_BackwardCompatible_GL3::ReleaseTexture (Rml::TextureHandle texture_handle) [override]
Definition at line 746 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References glDeleteTextures.
RenderCompiledGeometry()
void RenderInterface_BackwardCompatible_GL3::RenderCompiledGeometry (Rml::CompiledGeometryHandle geometry, const Rml::Vector2f & translation) [override]
Definition at line 508 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References Gfx::CompiledGeometryData::draw_count, GL_TEXTURE_2D, GL_TRIANGLES, GL_UNSIGNED_INT, glBindTexture, glBindVertexArray, glDrawElements, glUniform2fv, glUseProgram, Gfx::CompiledGeometryData::texture, TextureEnableWithoutBinding, Gfx::Transform, Gfx::Translate, and Gfx::CompiledGeometryData::vao.
Referenced by RenderGeometry().
RenderGeometry()
void RenderInterface_BackwardCompatible_GL3::RenderGeometry (Rml::Vertex * vertices, int num_vertices, int * indices, int num_indices, Rml::TextureHandle texture, const Rml::Vector2f & translation) [override]
Definition at line 449 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References CompileGeometry(), ReleaseCompiledGeometry(), and RenderCompiledGeometry().
Referenced by SetScissorRegion().
SetScissorRegion()
void RenderInterface_BackwardCompatible_GL3::SetScissorRegion (int x, int y, int width, int height) [override]
Definition at line 574 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
References GL_ALWAYS, GL_EQUAL, GL_FALSE, GL_KEEP, GL_REPLACE, GL_STENCIL_BUFFER_BIT, GL_TRUE, glClear, glColorMask, glScissor, glStencilFunc, glStencilOp, and RenderGeometry().
SetTransform()
void RenderInterface_BackwardCompatible_GL3::SetTransform (const Rml::Matrix4f * transform) [override]
Definition at line 751 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
Referenced by BeginFrame().
SetViewport()
void RenderInterface_BackwardCompatible_GL3::SetViewport (int viewport_width, int viewport_height)
Definition at line 332 of file RmlUi_Renderer_BackwardCompatible_GL3.cpp.
Member Data Documentation
TextureEnableWithoutBinding
const Rml::TextureHandle RenderInterface_BackwardCompatible_GL3::TextureEnableWithoutBinding = Rml::TextureHandle(-1) [static]
Definition at line 83 of file RmlUi_Renderer_BackwardCompatible_GL3.h.
Referenced by RenderCompiledGeometry().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_BackwardCompatible/RmlUi_Renderer_BackwardCompatible_GL3.h
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_BackwardCompatible/RmlUi_Renderer_BackwardCompatible_GL3.cpp