Techstorm::FileSystemRegistry Class Reference
#include <FileSystem.h>
Public Member Functions
FileSystemRegistry ()
void init (const char *rootPath)
Initializes the specified root path.
std::shared_ptr< FileMeta > GetFileMeta (std::string const &key)
Gets the file meta.
void loadFile (std::shared_ptr< RegisteredFile > const &file)
Loads the file.
std::shared_ptr< RegisteredFile > getFile (std::string const &key, bool loadIfNotLoaded=true)
Gets the file.
void addLoadFunction (std::string const &extension, std::function< std::any(std::shared_ptr< FileMeta >)> const &loadFunc)
Adds the load function.
void addLoadOnRegisterExtension (std::string const &extension)
Adds the load on register extension.
Friends
class IProject
Additional Inherited Members
Static Public Member Functions inherited from Techstorm::Singleton< FileSystemRegistry >
static FileSystemRegistry & Instance ()
Retrieves the current singleton instance as a reference.
Detailed Description
Definition at line 42 of file FileSystem.h.
Constructor & Destructor Documentation
FileSystemRegistry()
Techstorm::FileSystemRegistry::FileSystemRegistry () [inline]
Definition at line 45 of file FileSystem.h.
Member Function Documentation
addLoadFunction()
void Techstorm::FileSystemRegistry::addLoadFunction (std::string const & extension, std::function< std::any(std::shared_ptr< FileMeta >)> const & loadFunc) [inline]
Adds the load function.
Parameters
extension The extension.
loadFunc The load function.
Definition at line 94 of file FileSystem.h.
Referenced by Techstorm::AddFileRegistryLoadFunction().
addLoadOnRegisterExtension()
void Techstorm::FileSystemRegistry::addLoadOnRegisterExtension (std::string const & extension) [inline]
Adds the load on register extension.
Parameters
extension The extension.
Definition at line 100 of file FileSystem.h.
Referenced by Techstorm::AddFileRegistryLoadOnRegisterExtension().
getFile()
std::shared_ptr< RegisteredFile > Techstorm::FileSystemRegistry::getFile (std::string const & key, bool loadIfNotLoaded = true) [inline]
Gets the file.
Parameters
key The key.
loadIfNotLoaded if set to true [load if not loaded].
Returns
Definition at line 80 of file FileSystem.h.
References loadFile().
Referenced by Techstorm::GetFile(), and main().
GetFileMeta()
std::shared_ptr< Techstorm::FileMeta > Techstorm::FileSystemRegistry::GetFileMeta (std::string const & key)
Gets the file meta.
Parameters
key The key.
Returns
Definition at line 80 of file FileSystem.cpp.
Referenced by Techstorm::GetFileMeta().
init()
void Techstorm::FileSystemRegistry::init (const char * rootPath)
Initializes the specified root path.
Parameters
rootPath The root path.
Definition at line 44 of file FileSystem.cpp.
References Techstorm::FileMeta::extension, Techstorm::FileMeta::filename, loadFile(), and Techstorm::FileMeta::path.
Referenced by Techstorm::InitializeFileRegistry().
loadFile()
void Techstorm::FileSystemRegistry::loadFile (std::shared_ptr< RegisteredFile > const & file) [inline]
Loads the file.
Parameters
file The file.
Definition at line 64 of file FileSystem.h.
Referenced by getFile(), and init().
Friends And Related Symbol Documentation
IProject
friend class IProject [friend]
Definition at line 116 of file FileSystem.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/fs/FileSystem.h
C:/Dev/Techstorm-v5/src/engine/fs/FileSystem.cpp