Project Class Reference
Write your project code here or do what you want with it. However, you MUST implement the IProject interface somehow and set the project reference! See Techstorm::IProject for more information on this.
#include <project.h>
Public Member Functions
Project ()
int run (int argc, char *argv[]) override
void init (int argc, char *argv[]) override
void preInit () override
Detailed Description
Write your project code here or do what you want with it. However, you MUST implement the IProject interface somehow and set the project reference! See Techstorm::IProject for more information on this.
Definition at line 10 of file project.h.
Constructor & Destructor Documentation
Project()
Project::Project () [inline]
Definition at line 13 of file project.h.
Member Function Documentation
init()
void Project::init (int argc, char * argv[]) [override]
Techstorm::IProject::init
Definition at line 9 of file project.cpp.
Referenced by initProject().
preInit()
void Project::preInit () [override]
Techstorm::IProject::preInit
Definition at line 13 of file project.cpp.
Referenced by initProject().
run()
int Project::run (int argc, char * argv[]) [override]
Techstorm::IProject::run
Definition at line 4 of file project.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/project/project.h
C:/Dev/Techstorm-v5/src/project/project.cpp