Vec3 Struct Reference
#include <ChunkTesting.h>
Public Member Functions
Vec3 ()
Vec3 (float x, float y, float z)
Vec3 (const Vector3 &other)
Vec3 cross (const Vec3 &other) const
Vec3 operator- (const Vec3 &other) const
Vec3 normalize () const
Vector3 toVector3 () const
Public Attributes
float x
float y
float z
Detailed Description
Definition at line 25 of file ChunkTesting.h.
Constructor & Destructor Documentation
Vec3() [1/3]
Vec3::Vec3 () [inline]
Definition at line 28 of file ChunkTesting.h.
Referenced by cross(), normalize(), and operator-().
Vec3() [2/3]
Vec3::Vec3 (float x, float y, float z) [inline]
Definition at line 29 of file ChunkTesting.h.
Vec3() [3/3]
Vec3::Vec3 (const Vector3 & other) [inline]
Definition at line 30 of file ChunkTesting.h.
Member Function Documentation
cross()
Vec3 Vec3::cross (const Vec3 & other) const [inline]
Definition at line 33 of file ChunkTesting.h.
References Vec3(), x, y, and z.
Referenced by generateMeshData().
normalize()
Vec3 Vec3::normalize () const [inline]
Definition at line 47 of file ChunkTesting.h.
References Vec3(), x, y, and z.
Referenced by generateMeshData().
operator-()
Vec3 Vec3::operator- (const Vec3 & other) const [inline]
Definition at line 42 of file ChunkTesting.h.
References Vec3(), x, y, and z.
toVector3()
Vector3 Vec3::toVector3 () const [inline]
Definition at line 52 of file ChunkTesting.h.
References x, y, and z.
Member Data Documentation
x
float Vec3::x
Definition at line 26 of file ChunkTesting.h.
Referenced by cross(), generateMeshData(), normalize(), operator-(), and toVector3().
y
float Vec3::y
Definition at line 26 of file ChunkTesting.h.
Referenced by cross(), generateMeshData(), normalize(), operator-(), and toVector3().
z
float Vec3::z
Definition at line 26 of file ChunkTesting.h.
Referenced by cross(), generateMeshData(), normalize(), operator-(), and toVector3().
The documentation for this struct was generated from the following file:
C:/Dev/Techstorm-v5/src/application/prototyping/ChunkTesting.h