Generator Class Reference
#include <generator.hpp>
Public Member Functions
Generator (int max)
float get_random_number ()
returns a random number between -1.0 and 1.0
std::vector< std::vector< std::vector< float > > > generate_random_grid ()
std::vector< std::vector< std::vector< float > > > generate_sphere (float centerX, float centerY, float centerZ, float radius)
std::vector< std::vector< std::vector< float > > > generate_nested_spheres ()
std::vector< std::vector< std::vector< float > > > read_grid_from_file (const char *path)
Public Attributes
int GRID_MAX
Detailed Description
Definition at line 7 of file generator.hpp.
Constructor & Destructor Documentation
Generator()
Generator::Generator (int max)
Definition at line 16 of file generator.cpp.
References GRID_MAX.
Member Function Documentation
generate_nested_spheres()
std::vector< std::vector< std::vector< float > > > Generator::generate_nested_spheres ()
Definition at line 54 of file generator.cpp.
References GRID_MAX.
generate_random_grid()
std::vector< std::vector< std::vector< float > > > Generator::generate_random_grid ()
Definition at line 21 of file generator.cpp.
References get_random_number(), and GRID_MAX.
generate_sphere()
std::vector< std::vector< std::vector< float > > > Generator::generate_sphere (float centerX, float centerY, float centerZ, float radius)
Definition at line 34 of file generator.cpp.
References GRID_MAX.
get_random_number()
float Generator::get_random_number ()
returns a random number between -1.0 and 1.0
Returns
float
Definition at line 7 of file generator.cpp.
Referenced by generate_random_grid().
read_grid_from_file()
std::vector< std::vector< std::vector< float > > > Generator::read_grid_from_file (const char * path)
Definition at line 81 of file generator.cpp.
References GRID_MAX.
Referenced by main().
Member Data Documentation
GRID_MAX
int Generator::GRID_MAX
Definition at line 10 of file generator.hpp.
Referenced by generate_nested_spheres(), generate_random_grid(), generate_sphere(), Generator(), and read_grid_from_file().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/prototyping/generator.hpp
C:/Dev/Techstorm-v5/src/application/prototyping/generator.cpp