C:/Dev/Techstorm-v5/src/application/main.cpp File Reference
#include <Common.h>
#include <modding/ScriptingAPI.h>
#include <renderer/Renderer.h>
#include <renderer/WindowDecorations.h>
#include <conf/Config.h>
#include <project.h>
#include <raylib.h>
#include <thread>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 12 of file main.cpp.
References Techstorm::WindowDecorations::height, Techstorm::WindowDecorations::icon, Techstorm::ScriptingAPI::InitializeScripting(), Techstorm::Renderer::mCamera, PROJECT_TYPENAME, Techstorm::ScriptingAPI::RegisterLua(), Techstorm::Renderer::render(), Techstorm::WindowDecorations::targetFPS, Techstorm::Renderer::texture(), Techstorm::WindowDecorations::title, TS_ASSET_DIR, Techstorm::Renderer::update(), and Techstorm::WindowDecorations::width.