Techstorm::ConfigFileRegistry Class Reference
#include <Config.h>
Public Member Functions
ConfigFileRegistry ()
~ConfigFileRegistry ()
void readConfigFiles ()
void readConfigFile (const std::string &name)
void writeConfigFiles ()
void registerConfigFiles (const std::string &searchPath)
void registerConfigFile (const std::string &name, const std::string &path)
void unregisterConfigFiles ()
void unregisterConfigFile (const std::string &name)
libconfig::Setting & lookup (const std::string &name)
Public Attributes
std::unordered_map< std::string, std::shared_ptr< RegisteredFile > > mConfigFiles
Additional Inherited Members
Static Public Member Functions inherited from Techstorm::Singleton< ConfigFileRegistry >
static ConfigFileRegistry & Instance ()
Retrieves the current singleton instance as a reference.
Detailed Description
Definition at line 9 of file Config.h.
Constructor & Destructor Documentation
ConfigFileRegistry()
Techstorm::ConfigFileRegistry::ConfigFileRegistry ()
Definition at line 18 of file Config.cpp.
References Techstorm::AddFileRegistryLoadFunction(), and LoadConfigFile().
~ConfigFileRegistry()
Techstorm::ConfigFileRegistry::~ConfigFileRegistry ()
Definition at line 23 of file Config.cpp.
Member Function Documentation
lookup()
libconfig::Setting & Techstorm::ConfigFileRegistry::lookup (const std::string & name)
Definition at line 56 of file Config.cpp.
References Techstorm::GetFile().
readConfigFile()
void Techstorm::ConfigFileRegistry::readConfigFile (const std::string & name)
Definition at line 31 of file Config.cpp.
References Techstorm::GetFile().
readConfigFiles()
void Techstorm::ConfigFileRegistry::readConfigFiles ()
Definition at line 27 of file Config.cpp.
registerConfigFile()
void Techstorm::ConfigFileRegistry::registerConfigFile (const std::string & name, const std::string & path)
Definition at line 44 of file Config.cpp.
registerConfigFiles()
void Techstorm::ConfigFileRegistry::registerConfigFiles (const std::string & searchPath)
Definition at line 40 of file Config.cpp.
unregisterConfigFile()
void Techstorm::ConfigFileRegistry::unregisterConfigFile (const std::string & name)
Definition at line 52 of file Config.cpp.
unregisterConfigFiles()
void Techstorm::ConfigFileRegistry::unregisterConfigFiles ()
Definition at line 48 of file Config.cpp.
writeConfigFiles()
void Techstorm::ConfigFileRegistry::writeConfigFiles ()
Definition at line 36 of file Config.cpp.
Member Data Documentation
mConfigFiles
std::unordered_map<std::string, std::shared_ptr<RegisteredFile> > Techstorm::ConfigFileRegistry::mConfigFiles
Definition at line 25 of file Config.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/conf/Config.h
C:/Dev/Techstorm-v5/src/engine/conf/Config.cpp