RenderInterface_GL3 Class Reference
#include <RmlUi_Renderer_GL3.h>
Public Member Functions
RenderInterface_GL3 ()
~RenderInterface_GL3 ()
operator bool () const
void SetViewport (int viewport_width, int viewport_height)
void BeginFrame ()
void EndFrame ()
void Clear ()
Rml::CompiledGeometryHandle CompileGeometry (Rml::Span< const Rml::Vertex > vertices, Rml::Span< const int > indices) override
void RenderGeometry (Rml::CompiledGeometryHandle handle, Rml::Vector2f translation, Rml::TextureHandle texture) override
void ReleaseGeometry (Rml::CompiledGeometryHandle handle) override
Rml::TextureHandle LoadTexture (Rml::Vector2i &texture_dimensions, const Rml::String &source) override
Rml::TextureHandle GenerateTexture (Rml::Span< const Rml::byte > source_data, Rml::Vector2i source_dimensions) override
void ReleaseTexture (Rml::TextureHandle texture_handle) override
void EnableScissorRegion (bool enable) override
void SetScissorRegion (Rml::Rectanglei region) override
void EnableClipMask (bool enable) override
void RenderToClipMask (Rml::ClipMaskOperation mask_operation, Rml::CompiledGeometryHandle geometry, Rml::Vector2f translation) override
void SetTransform (const Rml::Matrix4f *transform) override
Rml::LayerHandle PushLayer () override
void CompositeLayers (Rml::LayerHandle source, Rml::LayerHandle destination, Rml::BlendMode blend_mode, Rml::Span< const Rml::CompiledFilterHandle > filters) override
void PopLayer () override
Rml::TextureHandle SaveLayerAsTexture () override
Rml::CompiledFilterHandle SaveLayerAsMaskImage () override
Rml::CompiledFilterHandle CompileFilter (const Rml::String &name, const Rml::Dictionary &parameters) override
void ReleaseFilter (Rml::CompiledFilterHandle filter) override
Rml::CompiledShaderHandle CompileShader (const Rml::String &name, const Rml::Dictionary &parameters) override
void RenderShader (Rml::CompiledShaderHandle shader_handle, Rml::CompiledGeometryHandle geometry_handle, Rml::Vector2f translation, Rml::TextureHandle texture) override
void ReleaseShader (Rml::CompiledShaderHandle effect_handle) override
Static Public Attributes
static constexpr Rml::TextureHandle TextureEnableWithoutBinding = Rml::TextureHandle(-1)
static constexpr Rml::TextureHandle TexturePostprocess = Rml::TextureHandle(-2)
Detailed Description
Definition at line 44 of file RmlUi_Renderer_GL3.h.
Constructor & Destructor Documentation
RenderInterface_GL3()
RenderInterface_GL3::RenderInterface_GL3 ()
Definition at line 778 of file RmlUi_Renderer_GL3.cpp.
References CompileGeometry().
~RenderInterface_GL3()
RenderInterface_GL3::~RenderInterface_GL3 ()
Definition at line 790 of file RmlUi_Renderer_GL3.cpp.
References ReleaseGeometry().
Member Function Documentation
BeginFrame()
void RenderInterface_GL3::BeginFrame ()
Definition at line 812 of file RmlUi_Renderer_GL3.cpp.
References GL_ACTIVE_TEXTURE, GL_ALWAYS, GL_BLEND, GL_BLEND_DST_ALPHA, GL_BLEND_DST_RGB, GL_BLEND_EQUATION_ALPHA, GL_BLEND_EQUATION_RGB, GL_BLEND_SRC_ALPHA, GL_BLEND_SRC_RGB, GL_COLOR_BUFFER_BIT, GL_COLOR_CLEAR_VALUE, GL_COLOR_WRITEMASK, GL_CULL_FACE, GL_DEPTH_TEST, GL_FRAMEBUFFER, GL_FRAMEBUFFER_SRGB, GL_FUNC_ADD, GL_KEEP, GL_ONE, GL_ONE_MINUS_SRC_ALPHA, GL_SCISSOR_BOX, GL_SCISSOR_TEST, GL_STENCIL_BACK_FAIL, GL_STENCIL_BACK_FUNC, GL_STENCIL_BACK_PASS_DEPTH_FAIL, GL_STENCIL_BACK_PASS_DEPTH_PASS, GL_STENCIL_BACK_REF, GL_STENCIL_BACK_VALUE_MASK, GL_STENCIL_BACK_WRITEMASK, GL_STENCIL_CLEAR_VALUE, GL_STENCIL_FAIL, GL_STENCIL_FUNC, GL_STENCIL_PASS_DEPTH_FAIL, GL_STENCIL_PASS_DEPTH_PASS, GL_STENCIL_REF, GL_STENCIL_TEST, GL_STENCIL_VALUE_MASK, GL_STENCIL_WRITEMASK, GL_TEXTURE0, GL_VIEWPORT, glActiveTexture, glBindFramebuffer, glBlendEquation, glBlendFunc, glClear, glClearColor, glClearStencil, glDisable, glEnable, glGetBooleanv, glGetFloatv, glGetIntegerv, glIsEnabled, glStencilFunc, glStencilMask, glStencilOp, glViewport, None, and SetTransform().
Clear()
void RenderInterface_GL3::Clear ()
Definition at line 972 of file RmlUi_Renderer_GL3.cpp.
References GL_COLOR_BUFFER_BIT, glClear, and glClearColor.
CompileFilter()
Rml::CompiledFilterHandle RenderInterface_GL3::CompileFilter (const Rml::String & name, const Rml::Dictionary & parameters) [override]
Definition at line 1504 of file RmlUi_Renderer_GL3.cpp.
References CompiledFilter::blend_factor, Blur, CompiledFilter::color, CompiledFilter::color_matrix, ColorMatrix, DropShadow, Invalid, CompiledFilter::offset, Passthrough, CompiledFilter::sigma, and CompiledFilter::type.
CompileGeometry()
Rml::CompiledGeometryHandle RenderInterface_GL3::CompileGeometry (Rml::Span< const Rml::Vertex > vertices, Rml::Span< const int > indices) [override]
Definition at line 978 of file RmlUi_Renderer_GL3.cpp.
References Gfx::Color0, Gfx::CompiledGeometryData::draw_count, GL_ARRAY_BUFFER, GL_ELEMENT_ARRAY_BUFFER, GL_FALSE, GL_FLOAT, GL_STATIC_DRAW, GL_TRUE, GL_UNSIGNED_BYTE, glBindBuffer, glBindVertexArray, glBufferData, glEnableVertexAttribArray, glGenBuffers, glGenVertexArrays, glVertexAttribPointer, Gfx::CompiledGeometryData::ibo, Gfx::Position, Gfx::TexCoord0, Gfx::CompiledGeometryData::vao, and Gfx::CompiledGeometryData::vbo.
Referenced by RenderInterface_GL3().
CompileShader()
Rml::CompiledShaderHandle RenderInterface_GL3::CompileShader (const Rml::String & name, const Rml::Dictionary & parameters) [override]
Definition at line 1636 of file RmlUi_Renderer_GL3.cpp.
References Conic, Creation, Gradient, Invalid, Linear, MAX_NUM_STOPS, Radial, RepeatingConic, RepeatingLinear, RepeatingRadial, shader, and CompiledShader::type.
CompositeLayers()
void RenderInterface_GL3::CompositeLayers (Rml::LayerHandle source, Rml::LayerHandle destination, Rml::BlendMode blend_mode, Rml::Span< const Rml::CompiledFilterHandle > filters) [override]
Definition at line 1907 of file RmlUi_Renderer_GL3.cpp.
References GL_BLEND, GL_FRAMEBUFFER, glBindFramebuffer, glDisable, glEnable, and Passthrough.
EnableClipMask()
void RenderInterface_GL3::EnableClipMask (bool enable) [override]
Definition at line 1115 of file RmlUi_Renderer_GL3.cpp.
References GL_STENCIL_TEST, glDisable, and glEnable.
EnableScissorRegion()
void RenderInterface_GL3::EnableScissorRegion (bool enable) [override]
Definition at line 1103 of file RmlUi_Renderer_GL3.cpp.
Referenced by SaveLayerAsTexture().
EndFrame()
void RenderInterface_GL3::EndFrame ()
Definition at line 896 of file RmlUi_Renderer_GL3.cpp.
References Gfx::FramebufferData::framebuffer, GL_BACK, GL_BLEND, GL_COLOR_BUFFER_BIT, GL_CULL_FACE, GL_DEPTH_TEST, GL_DRAW_FRAMEBUFFER, GL_FRAMEBUFFER, GL_FRONT, GL_NEAREST, GL_READ_FRAMEBUFFER, GL_SCISSOR_TEST, GL_STENCIL_TEST, GL_TEXTURE0, glActiveTexture, glBindFramebuffer, glBlendEquationSeparate, glBlendFuncSeparate, glBlitFramebuffer, glClearColor, glClearStencil, glColorMask, glDisable, glEnable, glScissor, glStencilFuncSeparate, glStencilMaskSeparate, glStencilOpSeparate, glViewport, Gfx::FramebufferData::height, Passthrough, and Gfx::FramebufferData::width.
GenerateTexture()
Rml::TextureHandle RenderInterface_GL3::GenerateTexture (Rml::Span< const Rml::byte > source_data, Rml::Vector2i source_dimensions) [override]
Definition at line 1270 of file RmlUi_Renderer_GL3.cpp.
References GL_LINEAR, GL_REPEAT, GL_RGBA, GL_RGBA8, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNSIGNED_BYTE, glBindTexture, glGenTextures, glTexImage2D, and glTexParameteri.
Referenced by RenderInterface_GL3_SDL::LoadTexture(), LoadTexture(), and SaveLayerAsTexture().
LoadTexture()
Rml::TextureHandle RenderInterface_GL3::LoadTexture (Rml::Vector2i & texture_dimensions, const Rml::String & source) [override]
Definition at line 1191 of file RmlUi_Renderer_GL3.cpp.
References TGAHeader::bitsPerPixel, TGAHeader::dataType, GenerateTexture(), TGAHeader::height, TGAHeader::imageDescriptor, and TGAHeader::width.
operator bool()
RenderInterface_GL3::operator bool () const [inline], [explicit]
Definition at line 50 of file RmlUi_Renderer_GL3.h.
PopLayer()
void RenderInterface_GL3::PopLayer () [override]
Definition at line 1940 of file RmlUi_Renderer_GL3.cpp.
References GL_FRAMEBUFFER, and glBindFramebuffer.
PushLayer()
Rml::LayerHandle RenderInterface_GL3::PushLayer () [override]
Definition at line 1897 of file RmlUi_Renderer_GL3.cpp.
References GL_COLOR_BUFFER_BIT, GL_FRAMEBUFFER, glBindFramebuffer, and glClear.
ReleaseFilter()
void RenderInterface_GL3::ReleaseFilter (Rml::CompiledFilterHandle filter) [override]
Definition at line 1616 of file RmlUi_Renderer_GL3.cpp.
ReleaseGeometry()
void RenderInterface_GL3::ReleaseGeometry (Rml::CompiledGeometryHandle handle) [override]
Definition at line 1054 of file RmlUi_Renderer_GL3.cpp.
References glDeleteBuffers, glDeleteVertexArrays, Gfx::CompiledGeometryData::ibo, Gfx::CompiledGeometryData::vao, and Gfx::CompiledGeometryData::vbo.
Referenced by ~RenderInterface_GL3().
ReleaseShader()
void RenderInterface_GL3::ReleaseShader (Rml::CompiledShaderHandle effect_handle) [override]
Definition at line 1755 of file RmlUi_Renderer_GL3.cpp.
ReleaseTexture()
void RenderInterface_GL3::ReleaseTexture (Rml::TextureHandle texture_handle) [override]
Definition at line 1475 of file RmlUi_Renderer_GL3.cpp.
References glDeleteTextures.
RenderGeometry()
void RenderInterface_GL3::RenderGeometry (Rml::CompiledGeometryHandle handle, Rml::Vector2f translation, Rml::TextureHandle texture) [override]
Definition at line 1023 of file RmlUi_Renderer_GL3.cpp.
References Color, Gfx::CompiledGeometryData::draw_count, GL_TEXTURE_2D, GL_TRIANGLES, GL_UNSIGNED_INT, glBindTexture, glBindVertexArray, glDrawElements, Texture, TextureEnableWithoutBinding, TexturePostprocess, and Gfx::CompiledGeometryData::vao.
Referenced by RenderToClipMask().
RenderShader()
void RenderInterface_GL3::RenderShader (Rml::CompiledShaderHandle shader_handle, Rml::CompiledGeometryHandle geometry_handle, Rml::Vector2f translation, Rml::TextureHandle texture) [override]
Definition at line 1702 of file RmlUi_Renderer_GL3.cpp.
References Creation, Dimensions, Gfx::CompiledGeometryData::draw_count, Func, GL_TRIANGLES, GL_UNSIGNED_INT, glBindVertexArray, glDrawElements, glUniform1f, glUniform1fv, glUniform1i, glUniform2f, glUniform4fv, Gradient, Invalid, NumStops, P, shader, StopColors, StopPositions, CompiledShader::type, V, Value, and Gfx::CompiledGeometryData::vao.
RenderToClipMask()
void RenderInterface_GL3::RenderToClipMask (Rml::ClipMaskOperation mask_operation, Rml::CompiledGeometryHandle geometry, Rml::Vector2f translation) [override]
Definition at line 1123 of file RmlUi_Renderer_GL3.cpp.
References GL_ALWAYS, GL_EQUAL, GL_FALSE, GL_INCR, GL_KEEP, GL_REPLACE, GL_STENCIL_BUFFER_BIT, GL_STENCIL_REF, GL_STENCIL_TEST, GL_TRUE, glClear, glColorMask, glGetIntegerv, glIsEnabled, glStencilFunc, glStencilOp, and RenderGeometry().
SaveLayerAsMaskImage()
Rml::CompiledFilterHandle RenderInterface_GL3::SaveLayerAsMaskImage () [override]
Definition at line 1986 of file RmlUi_Renderer_GL3.cpp.
References Gfx::FramebufferData::framebuffer, GL_BLEND, GL_FRAMEBUFFER, glBindFramebuffer, glDisable, glEnable, MaskImage, Passthrough, and CompiledFilter::type.
SaveLayerAsTexture()
Rml::TextureHandle RenderInterface_GL3::SaveLayerAsTexture () [override]
Definition at line 1946 of file RmlUi_Renderer_GL3.cpp.
References EnableScissorRegion(), Gfx::FramebufferData::framebuffer, GenerateTexture(), GL_COLOR_BUFFER_BIT, GL_DRAW_FRAMEBUFFER, GL_FRAMEBUFFER, GL_NEAREST, GL_READ_FRAMEBUFFER, GL_TEXTURE_2D, glBindFramebuffer, glBindTexture, glBlitFramebuffer, glCopyTexSubImage2D, and Gfx::FramebufferData::height.
SetScissorRegion()
void RenderInterface_GL3::SetScissorRegion (Rml::Rectanglei region) [override]
Definition at line 1110 of file RmlUi_Renderer_GL3.cpp.
SetTransform()
void RenderInterface_GL3::SetTransform (const Rml::Matrix4f * transform) [override]
Definition at line 1480 of file RmlUi_Renderer_GL3.cpp.
Referenced by BeginFrame().
SetViewport()
void RenderInterface_GL3::SetViewport (int viewport_width, int viewport_height)
Definition at line 805 of file RmlUi_Renderer_GL3.cpp.
Member Data Documentation
TextureEnableWithoutBinding
constexpr Rml::TextureHandle RenderInterface_GL3::TextureEnableWithoutBinding = Rml::TextureHandle(-1) [static], [constexpr]
Definition at line 99 of file RmlUi_Renderer_GL3.h.
Referenced by RenderGeometry().
TexturePostprocess
constexpr Rml::TextureHandle RenderInterface_GL3::TexturePostprocess = Rml::TextureHandle(-2) [static], [constexpr]
Definition at line 101 of file RmlUi_Renderer_GL3.h.
Referenced by RenderGeometry().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_Renderer_GL3.h
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_Renderer_GL3.cpp