PhysicsEngine Class Reference
#include <PhysicsPrototype.h>
Public Member Functions
PhysicsEngine ()=default
void init (const AllocatedPhysicsResources resources)
void update (const float cDeltaTime)
void optimizeBroadPhase ()
JPH::BodyInterface & getBodyInterface () const
Public Attributes
JPH::PhysicsSystem * mPhysicsSystem = nullptr
Additional Inherited Members
Static Public Member Functions inherited from Techstorm::Singleton< PhysicsEngine >
static PhysicsEngine & Instance ()
Retrieves the current singleton instance as a reference.
Detailed Description
Definition at line 267 of file PhysicsPrototype.h.
Constructor & Destructor Documentation
PhysicsEngine()
PhysicsEngine::PhysicsEngine () [default]
Member Function Documentation
getBodyInterface()
JPH::BodyInterface & PhysicsEngine::getBodyInterface () const [inline]
Definition at line 345 of file PhysicsPrototype.h.
Referenced by PrototypePhysicsTerrain().
init()
void PhysicsEngine::init (const AllocatedPhysicsResources resources) [inline]
Definition at line 271 of file PhysicsPrototype.h.
References AllocatedPhysicsResources::cMaxBodies, AllocatedPhysicsResources::cMaxBodyPairs, AllocatedPhysicsResources::cMaxContactConstraints, AllocatedPhysicsResources::cNumBodyMutexes, mPhysicsSystem, and AllocatedPhysicsResources::preAllocatedMemory.
Referenced by PrototypePhysicsTerrain().
optimizeBroadPhase()
void PhysicsEngine::optimizeBroadPhase () [inline]
Definition at line 341 of file PhysicsPrototype.h.
References mPhysicsSystem.
Referenced by PrototypePhysicsTerrain().
update()
void PhysicsEngine::update (const float cDeltaTime) [inline]
Definition at line 337 of file PhysicsPrototype.h.
References mPhysicsSystem.
Referenced by PrototypePhysicsTerrain().
Member Data Documentation
mPhysicsSystem
JPH::PhysicsSystem* PhysicsEngine::mPhysicsSystem = nullptr
Definition at line 346 of file PhysicsPrototype.h.
Referenced by init(), optimizeBroadPhase(), and update().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/application/prototyping/PhysicsPrototype.h