Techstorm Namespace Reference
Namespaces
namespace Application
namespace BroadPhaseLayers
namespace DevTools
namespace Layers
Classes
class abstract
This is an abstract interface singleton that all projects must implement and set the ProjectReference singleton to their project. If this boilerplate code is not done, Techstorm will not know what to run. In terms of functionality, this interface just holds the functions and variables that Techstorm will call (besides some initialization). Do not directly call window code in here or your project will crash!
struct AllocatedPhysicsResources
class BPLayerInterfaceImpl
class ConfigFileRegistry
struct EngineConfig
struct ExportedFunction
class FileMeta
class FileSystemRegistry
class GameCamera
Represents a camera wherein the world is rendered and viewed from.
class GameObject
A game object that can be rendered to the screen. Inherits from IGameObject, and already provides the basic rendering functionality. If you override this class, you should inherit the function.
class GameObjectRegistry
Game object registry, it stores all game objects in the world and manages their updating, rendering, destruction, creation, etc.
class Gate
A class that acts as, well, a gate! It is essentially as a piece of machinery on an assembly line. Please do note, that this is a template class and is not meant to be used directly. Please see GameObjectRegistry for more information and an example.
class GlobalsContainer
class InputAction
Serves as a search key/input category for the input system. Please pay attention when using this because any slight change in InputAction keys will give you entirely different input results.
class InputRegistry
The input registry is used to register InputActions (InputAction) and their callbacks. Remember that this is a singleton, so you may use this statically.
class LayerRegistry
class MyBodyActivationListener
class ObjectContactListener
class ObjectLayerPairFilterImpl
Class that determines if two object layers can collide.
class ObjectVsBroadPhaseLayerFilterImpl
Class that determines if an object layer can collide with a broadphase layer.
class PhysicsEngine
class PlaneObject
class RegisteredFile
class Renderer
Serves as the renderer for the game.
class ScriptingAPI
class Singleton
A singleton class, it does what singletons do. The template (T) must be the type that is inheriting from this class, otherwise there will be issues.
class TechstormEngine
struct Vec2
struct Vec3
struct Vec4
class Window
struct WindowDecorations
Window decorations are a set of parameters that are used to configure the window. This includes title, width, height, window config, and target FPS.
class World
Typedefs
using FilePathMeta = { const std::string cPath
using DirectoryFiles = std::vector< std::string >
using GameSettings = GameSettings { const int cMaxThreads=-1
Serves as the settings for the game. Please note that cMaxThreads must be at least 2. If you want Techstorm to decide, set cMaxThreads to -1.
using LuaLibraryRegistry = std::vector< sol::lib >
using LuaFunctionRegistry = std::unordered_map< std::string, ExportedFunction >
using Depth = int
Enumerations
enum class EReturnCode : int {
SUCCESSFUL_OPERATION
, SUCCESSFUL_OPERATION_WITH_WARNING
, SUCCESSFUL_OPERATION_WITH_CAUGHT_EXCEPTION
, ERROR_UNKNOWN = -1
,
ERROR_INVALID_ARGS = -2
, ERROR_INVALID_VALUE = -3
 }
enum class EInputType { INPUT_KEYBOARD
, INPUT_MOUSE
, INPUT_CONTROLLER
 }
The enumeration for the different input device categories. This is here because the input system is going to be expanded in the future and it will be useful to maintaining developer sanity.
enum class EInputTrigger {
INPUT_TRIGGER_PRESSED
, INPUT_TRIGGER_RELEASED
, INPUT_TRIGGER_DOWN
, INPUT_TRIGGER_UP
,
INPUT_TRIGGER_REPEAT
 }
What sort of action should trigger the InputAction? Please pay attention when using this because any slight change in InputAction keys will give you entirely different input results.
Functions
void InitHaptics ()
void SetControllerRumble (int controllerIndex, int leftMotorSpeed, int rightMotorSpeed)
void StartRumblingController (int controllerIndex, int leftMotorSpeed, int rightMotorSpeed)
void StopRumblingController (int controllerIndex)
ConfigFileRegistry & GetConfigFileRegistry ()
void InitializeConfigRegistry ()
libconfig::Setting & LookupConfig (const std::string &fileName, const std::string &lookupTarget)
bool FileSystemIsProperlyFormatted (const char *rootPath, const char *directoryMapPath)
FileSystemRegistry & GetFileSystemRegistry ()
void InitializeFileRegistry (const char *rootPath)
void AddFileRegistryLoadFunction (std::string extension, std::function< std::any(std::shared_ptr< FileMeta >)> loadFunc)
void AddFileRegistryLoadOnRegisterExtension (std::string const &extension)
std::shared_ptr< FileMeta > GetFileMeta (std::string key)
std::shared_ptr< RegisteredFile > GetFile (std::string key, bool loadIfNotLoaded=true)
InputRegistry & GetInputRegistry ()
Gets the current instance of the InputRegistry singleton InputRegistry. This is a quality of life function, and calling it like other singletons is perfectly okay.
int RegisterActionCallback (InputAction *action, std::function< void(InputAction *)> const &callback)
Registers a callback by using the provided action (InputAction) and the callback parameter values. This works as a key-value pair, where the key is the action and the value is the callback. This works the same way as the RegisterActionCallback function (InputRegistry::registerActionCallback), but it registers the callback in the current input registry (InputRegistry). This is simply a quality of life function, and calling it like other singletons is perfectly okay.
void UnregisterAction (InputAction *action)
Unregisters ALL callbacks for the provided InputAction; action (InputAction), and unregisters it from the current input registry (InputRegistry). This is simply a quality of life function, and calling it like other singletons is perfectly okay.
void UnregisterCallback (InputAction *action, int id)
Unregisters a specific callback, denoted by id, for the provided InputAction; action (InputAction). This is simply a quality of life function, and calling it like other singletons is perfectly okay.
template<typename T >
T & GetGlobal (const std::string &key)
template<typename T >
void SetGlobal (const std::string &key, const T &value)
Variables
const std::string cDirectoryName
Typedef Documentation
Depth
using Techstorm::Depth = typedef int
Definition at line 7 of file RenderLayer.h.
DirectoryFiles
using Techstorm::DirectoryFiles = typedef std::vector<std::string>
Definition at line 15 of file FileSystem.h.
FilePathMeta
using Techstorm::FilePathMeta = typedef { const std::string cPath
Definition at line 5 of file FilePathMeta.h.
GameSettings
using Techstorm::GameSettings = typedef GameSettings { const int cMaxThreads = -1
Serves as the settings for the game. Please note that cMaxThreads must be at least 2. If you want Techstorm to decide, set cMaxThreads to -1.
Definition at line 9 of file GameSettings.h.
LuaFunctionRegistry
using Techstorm::LuaFunctionRegistry = typedef std::unordered_map<std::string, ExportedFunction>
Definition at line 26 of file ScriptingAPI.h.
LuaLibraryRegistry
using Techstorm::LuaLibraryRegistry = typedef std::vector<sol::lib>
Definition at line 25 of file ScriptingAPI.h.
Enumeration Type Documentation
EInputTrigger
enum class Techstorm::EInputTrigger [strong]
What sort of action should trigger the InputAction? Please pay attention when using this because any slight change in InputAction keys will give you entirely different input results.
Enumerator
INPUT_TRIGGER_PRESSED
INPUT_TRIGGER_RELEASED
INPUT_TRIGGER_DOWN
INPUT_TRIGGER_UP
INPUT_TRIGGER_REPEAT
Definition at line 25 of file Input.h.
EInputType
enum class Techstorm::EInputType [strong]
The enumeration for the different input device categories. This is here because the input system is going to be expanded in the future and it will be useful to maintaining developer sanity.
Enumerator
INPUT_KEYBOARD
INPUT_MOUSE
INPUT_CONTROLLER
Definition at line 16 of file Input.h.
EReturnCode
enum class Techstorm::EReturnCode : int [strong]
Enumerator
SUCCESSFUL_OPERATION
SUCCESSFUL_OPERATION_WITH_WARNING
SUCCESSFUL_OPERATION_WITH_CAUGHT_EXCEPTION
ERROR_UNKNOWN
ERROR_INVALID_ARGS
ERROR_INVALID_VALUE
Definition at line 4 of file EReturnCode.h.
Function Documentation
AddFileRegistryLoadFunction()
void Techstorm::AddFileRegistryLoadFunction (std::string extension, std::function< std::any(std::shared_ptr< FileMeta >)> loadFunc)
Definition at line 24 of file FileSystem.cpp.
References Techstorm::FileSystemRegistry::addLoadFunction(), and GetFileSystemRegistry().
Referenced by Techstorm::ConfigFileRegistry::init(), and Techstorm::abstract< K, D, T >::preInit().
AddFileRegistryLoadOnRegisterExtension()
void Techstorm::AddFileRegistryLoadOnRegisterExtension (std::string const & extension)
Definition at line 29 of file FileSystem.cpp.
References Techstorm::FileSystemRegistry::addLoadOnRegisterExtension(), and GetFileSystemRegistry().
FileSystemIsProperlyFormatted()
bool Techstorm::FileSystemIsProperlyFormatted (const char * rootPath, const char * directoryMapPath)
Definition at line 9 of file FileSystem.cpp.
GetConfigFileRegistry()
Techstorm::ConfigFileRegistry & Techstorm::GetConfigFileRegistry ()
Definition at line 77 of file Config.cpp.
References Techstorm::Singleton< ConfigFileRegistry >::Instance().
GetFile()
std::shared_ptr< Techstorm::RegisteredFile > Techstorm::GetFile (std::string key, bool loadIfNotLoaded = true)
Definition at line 39 of file FileSystem.cpp.
References Techstorm::FileSystemRegistry::getFile(), and GetFileSystemRegistry().
Referenced by Techstorm::ConfigFileRegistry::lookup(), and Techstorm::ConfigFileRegistry::readConfigFile().
GetFileMeta()
std::shared_ptr< Techstorm::FileMeta > Techstorm::GetFileMeta (std::string key)
Definition at line 34 of file FileSystem.cpp.
References Techstorm::FileSystemRegistry::GetFileMeta(), and GetFileSystemRegistry().
GetFileSystemRegistry()
Techstorm::FileSystemRegistry & Techstorm::GetFileSystemRegistry ()
Definition at line 14 of file FileSystem.cpp.
Referenced by AddFileRegistryLoadFunction(), AddFileRegistryLoadOnRegisterExtension(), GetFile(), GetFileMeta(), and InitializeFileRegistry().
GetGlobal()
template<typename T >
T & Techstorm::GetGlobal (const std::string & key)
Definition at line 31 of file Globals.h.
References Techstorm::GlobalsContainer::get(), and Techstorm::Singleton< GlobalsContainer >::Instance().
GetInputRegistry()
InputRegistry & Techstorm::GetInputRegistry ()
Gets the current instance of the InputRegistry singleton InputRegistry. This is a quality of life function, and calling it like other singletons is perfectly okay.
Returns
A reference to the current instance of the InputRegistry singleton.
Definition at line 107 of file Input.h.
References Techstorm::Singleton< InputRegistry >::Instance().
Referenced by RegisterActionCallback(), UnregisterAction(), and UnregisterCallback().
InitHaptics()
void Techstorm::InitHaptics ()
Definition at line 19 of file Common.cpp.
InitializeConfigRegistry()
void Techstorm::InitializeConfigRegistry ()
Definition at line 79 of file Config.cpp.
References Techstorm::ConfigFileRegistry::init(), and Techstorm::Singleton< ConfigFileRegistry >::Instance().
InitializeFileRegistry()
void Techstorm::InitializeFileRegistry (const char * rootPath)
Definition at line 19 of file FileSystem.cpp.
References GetFileSystemRegistry(), and Techstorm::FileSystemRegistry::init().
Referenced by Techstorm::abstract< K, D, T >::preInit().
LookupConfig()
libconfig::Setting & Techstorm::LookupConfig (const std::string & fileName, const std::string & lookupTarget)
Definition at line 81 of file Config.cpp.
References Techstorm::Singleton< ConfigFileRegistry >::Instance(), and Techstorm::ConfigFileRegistry::lookup().
RegisterActionCallback()
int Techstorm::RegisterActionCallback (InputAction * action, std::function< void(InputAction *)> const & callback)
Registers a callback by using the provided action (InputAction) and the callback parameter values. This works as a key-value pair, where the key is the action and the value is the callback. This works the same way as the RegisterActionCallback function (InputRegistry::registerActionCallback), but it registers the callback in the current input registry (InputRegistry). This is simply a quality of life function, and calling it like other singletons is perfectly okay.
Parameters
action The action.
callback The callback.
Definition at line 116 of file Input.h.
References GetInputRegistry(), and Techstorm::InputRegistry::registerActionCallback().
SetControllerRumble()
void Techstorm::SetControllerRumble (int controllerIndex, int leftMotorSpeed, int rightMotorSpeed)
Definition at line 24 of file Common.cpp.
Referenced by StartRumblingController(), and StopRumblingController().
SetGlobal()
template<typename T >
void Techstorm::SetGlobal (const std::string & key, const T & value)
Definition at line 38 of file Globals.h.
References Techstorm::Singleton< GlobalsContainer >::Instance(), and Techstorm::GlobalsContainer::set().
StartRumblingController()
void Techstorm::StartRumblingController (int controllerIndex, int leftMotorSpeed, int rightMotorSpeed)
Definition at line 34 of file Common.cpp.
References SetControllerRumble().
StopRumblingController()
void Techstorm::StopRumblingController (int controllerIndex)
Definition at line 39 of file Common.cpp.
References SetControllerRumble().
UnregisterAction()
void Techstorm::UnregisterAction (InputAction * action)
Unregisters ALL callbacks for the provided InputAction; action (InputAction), and unregisters it from the current input registry (InputRegistry). This is simply a quality of life function, and calling it like other singletons is perfectly okay.
Parameters
action The action that will have its callbacks deleted.
Definition at line 123 of file Input.h.
References GetInputRegistry(), and Techstorm::InputRegistry::unregisterAction().
UnregisterCallback()
void Techstorm::UnregisterCallback (InputAction * action, int id)
Unregisters a specific callback, denoted by id, for the provided InputAction; action (InputAction). This is simply a quality of life function, and calling it like other singletons is perfectly okay.
Parameters
action The action that the callback lies in.
id The ID of the callback. You should have gotten it in the RegisterActionCallback or InputRegistry::registerActionCallback functions.
Definition at line 131 of file Input.h.
References GetInputRegistry(), and Techstorm::InputRegistry::unregisterCallback().
Variable Documentation
cDirectoryName
const std::string Techstorm::cDirectoryName
Definition at line 7 of file FilePathMeta.h.