C:/Dev/Techstorm-v5/src/application/prototyping/PrototypePhysicsTerrain.h File Reference
#include <utils/Singleton.h>
#include <iostream>
#include <cstdarg>
#include <thread>
#include <raylib.h>
#include "raymath.h"
#include <map>
#include <vector>
#include "../../include/rlights.h"
#include "rlgl.h"
#include "../../include/FastNoiseLite.h"
#include <stdio.h>
#include <string>
#include <utility>
#include <vadefs.h>
#include <ostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include "PhysicsPrototype.h"
#include "CircularMap.h"
Classes
class TerrainSector
class GameObject
class Terrain
struct Terrain::TriangleStruct
Macros
#define RLIGHTS_IMPLEMENTATION
#define GLSL_VERSION 100
#define CHUNK_SIZE 20
#define VIEW_DISTANCE 4
Functions
template<typename T >
void PushObject (T object, std::vector< T > &objects)
int PrototypePhysicsTerrain ()
Variables
std::stringstream terrainPieceOutput
Macro Definition Documentation
CHUNK_SIZE
#define CHUNK_SIZE 20
Definition at line 40 of file PrototypePhysicsTerrain.h.
GLSL_VERSION
#define GLSL_VERSION 100
Definition at line 34 of file PrototypePhysicsTerrain.h.
RLIGHTS_IMPLEMENTATION
#define RLIGHTS_IMPLEMENTATION
Definition at line 12 of file PrototypePhysicsTerrain.h.
VIEW_DISTANCE
#define VIEW_DISTANCE 4
Definition at line 41 of file PrototypePhysicsTerrain.h.
Function Documentation
PrototypePhysicsTerrain()
int PrototypePhysicsTerrain ()
Definition at line 483 of file PrototypePhysicsTerrain.h.
References camera, Terrain::cSampleCount, PhysicsEngine::getBodyInterface(), PhysicsEngine::init(), InitWindow(), Techstorm::Singleton< PhysicsEngine >::Instance(), Terrain::mdl, PhysicsEngine::optimizeBroadPhase(), GameObject::position, GameObject::setPosition(), GameObject::setVelocity(), shader, terrainPieceOutput, GameObject::texture, and PhysicsEngine::update().
PushObject()
template<typename T >
void PushObject (T object, std::vector< T > & objects)
Definition at line 477 of file PrototypePhysicsTerrain.h.
Variable Documentation
terrainPieceOutput
std::stringstream terrainPieceOutput
Definition at line 219 of file PrototypePhysicsTerrain.h.
Referenced by Terrain::generate(), and PrototypePhysicsTerrain().