TextInputMethodEditor_Win32 Class Reference
#include <RmlUi_Platform_Win32.h>
Public Member Functions
TextInputMethodEditor_Win32 ()
void OnActivate (Rml::TextInputContext *input_context) override
void OnDeactivate (Rml::TextInputContext *input_context) override
void OnDestroy (Rml::TextInputContext *input_context) override
bool IsComposing () const
void StartComposition ()
void CancelComposition ()
void SetComposition (Rml::StringView composition)
void ConfirmComposition (Rml::StringView composition)
void SetCursorPosition (int cursor_pos, bool update)
Detailed Description
Custom backend implementation of TextInputHandler to handle the system's Input Method Editor (IME). This version supports only one active text input context.
Definition at line 102 of file RmlUi_Platform_Win32.h.
Constructor & Destructor Documentation
TextInputMethodEditor_Win32()
TextInputMethodEditor_Win32::TextInputMethodEditor_Win32 ()
Definition at line 627 of file RmlUi_Platform_Win32.cpp.
Member Function Documentation
CancelComposition()
void TextInputMethodEditor_Win32::CancelComposition ()
Definition at line 671 of file RmlUi_Platform_Win32.cpp.
References IsComposing().
ConfirmComposition()
void TextInputMethodEditor_Win32::ConfirmComposition (Rml::StringView composition)
End the current composition by confirming the composition string.
Parameters
 in composition A string to confirm.
Definition at line 699 of file RmlUi_Platform_Win32.cpp.
References IsComposing(), and SetCursorPosition().
IsComposing()
bool TextInputMethodEditor_Win32::IsComposing () const
Check that a composition is currently active.
Returns
True if we are composing, false otherwise.
Definition at line 648 of file RmlUi_Platform_Win32.cpp.
Referenced by CancelComposition(), ConfirmComposition(), SetComposition(), and SetCursorPosition().
OnActivate()
void TextInputMethodEditor_Win32::OnActivate (Rml::TextInputContext * input_context) [override]
Definition at line 631 of file RmlUi_Platform_Win32.cpp.
OnDeactivate()
void TextInputMethodEditor_Win32::OnDeactivate (Rml::TextInputContext * input_context) [override]
Definition at line 636 of file RmlUi_Platform_Win32.cpp.
OnDestroy()
void TextInputMethodEditor_Win32::OnDestroy (Rml::TextInputContext * input_context) [override]
Definition at line 642 of file RmlUi_Platform_Win32.cpp.
SetComposition()
void TextInputMethodEditor_Win32::SetComposition (Rml::StringView composition)
Set the composition string.
Parameters
 in composition A string to be set.
Definition at line 686 of file RmlUi_Platform_Win32.cpp.
References IsComposing().
SetCursorPosition()
void TextInputMethodEditor_Win32::SetCursorPosition (int cursor_pos, bool update)
Set the cursor position within the composition.
Parameters
 in cursor_pos A character position of the cursor within the composition string.
 in update Update the cursor position within active input contexts.
Definition at line 717 of file RmlUi_Platform_Win32.cpp.
References IsComposing().
Referenced by ConfirmComposition().
StartComposition()
void TextInputMethodEditor_Win32::StartComposition ()
Definition at line 653 of file RmlUi_Platform_Win32.cpp.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_Platform_Win32.h
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_Platform_Win32.cpp