RenderInterface_GL2 Class Reference
#include <RmlUi_Renderer_GL2.h>
Public Member Functions
RenderInterface_GL2 ()
void SetViewport (int viewport_width, int viewport_height)
void BeginFrame ()
void EndFrame ()
void Clear ()
Rml::CompiledGeometryHandle CompileGeometry (Rml::Span< const Rml::Vertex > vertices, Rml::Span< const int > indices) override
void ReleaseGeometry (Rml::CompiledGeometryHandle geometry) override
void RenderGeometry (Rml::CompiledGeometryHandle handle, Rml::Vector2f translation, Rml::TextureHandle texture) override
Rml::TextureHandle LoadTexture (Rml::Vector2i &texture_dimensions, const Rml::String &source) override
Rml::TextureHandle GenerateTexture (Rml::Span< const Rml::byte > source, Rml::Vector2i source_dimensions) override
void ReleaseTexture (Rml::TextureHandle texture_handle) override
void EnableScissorRegion (bool enable) override
void SetScissorRegion (Rml::Rectanglei region) override
void EnableClipMask (bool enable) override
void RenderToClipMask (Rml::ClipMaskOperation operation, Rml::CompiledGeometryHandle geometry, Rml::Vector2f translation) override
void SetTransform (const Rml::Matrix4f *transform) override
Static Public Attributes
static const Rml::TextureHandle TextureEnableWithoutBinding = Rml::TextureHandle(-1)
Detailed Description
Definition at line 34 of file RmlUi_Renderer_GL2.h.
Constructor & Destructor Documentation
RenderInterface_GL2()
RenderInterface_GL2::RenderInterface_GL2 ()
Definition at line 52 of file RmlUi_Renderer_GL2.cpp.
Member Function Documentation
BeginFrame()
void RenderInterface_GL2::BeginFrame ()
Definition at line 60 of file RmlUi_Renderer_GL2.cpp.
References GL_ALWAYS, GL_BLEND, GL_KEEP, GL_ONE, GL_ONE_MINUS_SRC_ALPHA, GL_STENCIL_TEST, GL_TEXTURE, glBlendFunc, glEnable, glStencilFunc, glStencilMask, glStencilOp, and glViewport.
Clear()
void RenderInterface_GL2::Clear ()
Definition at line 90 of file RmlUi_Renderer_GL2.cpp.
References GL_COLOR_BUFFER_BIT, GL_STENCIL_BUFFER_BIT, glClear, glClearColor, and glClearStencil.
CompileGeometry()
Rml::CompiledGeometryHandle RenderInterface_GL2::CompileGeometry (Rml::Span< const Rml::Vertex > vertices, Rml::Span< const int > indices) [override]
Definition at line 97 of file RmlUi_Renderer_GL2.cpp.
EnableClipMask()
void RenderInterface_GL2::EnableClipMask (bool enable) [override]
Definition at line 155 of file RmlUi_Renderer_GL2.cpp.
References GL_STENCIL_TEST, glDisable, and glEnable.
EnableScissorRegion()
void RenderInterface_GL2::EnableScissorRegion (bool enable) [override]
Definition at line 142 of file RmlUi_Renderer_GL2.cpp.
References GL_SCISSOR_TEST, glDisable, and glEnable.
EndFrame()
void RenderInterface_GL2::EndFrame ()
Definition at line 88 of file RmlUi_Renderer_GL2.cpp.
GenerateTexture()
Rml::TextureHandle RenderInterface_GL2::GenerateTexture (Rml::Span< const Rml::byte > source, Rml::Vector2i source_dimensions) [override]
Definition at line 310 of file RmlUi_Renderer_GL2.cpp.
References GL_LINEAR, GL_REPEAT, GL_RGBA, GL_RGBA8, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNSIGNED_BYTE, glBindTexture, glGenTextures, glTexImage2D, and glTexParameteri.
Referenced by LoadTexture().
LoadTexture()
Rml::TextureHandle RenderInterface_GL2::LoadTexture (Rml::Vector2i & texture_dimensions, const Rml::String & source) [override]
Definition at line 231 of file RmlUi_Renderer_GL2.cpp.
References TGAHeader::bitsPerPixel, TGAHeader::dataType, GenerateTexture(), TGAHeader::height, TGAHeader::imageDescriptor, and TGAHeader::width.
ReleaseGeometry()
void RenderInterface_GL2::ReleaseGeometry (Rml::CompiledGeometryHandle geometry) [override]
Definition at line 103 of file RmlUi_Renderer_GL2.cpp.
ReleaseTexture()
void RenderInterface_GL2::ReleaseTexture (Rml::TextureHandle texture_handle) [override]
Definition at line 332 of file RmlUi_Renderer_GL2.cpp.
References glDeleteTextures.
RenderGeometry()
void RenderInterface_GL2::RenderGeometry (Rml::CompiledGeometryHandle handle, Rml::Vector2f translation, Rml::TextureHandle texture) [override]
Definition at line 108 of file RmlUi_Renderer_GL2.cpp.
References GL_FLOAT, GL_TEXTURE_2D, GL_TRIANGLES, GL_UNSIGNED_BYTE, GL_UNSIGNED_INT, glBindTexture, glDisable, glDrawElements, glEnable, and TextureEnableWithoutBinding.
Referenced by RenderInterface_GL2_SDL::RenderGeometry(), RenderInterface_GL2_SFML::RenderGeometry(), and RenderToClipMask().
RenderToClipMask()
void RenderInterface_GL2::RenderToClipMask (Rml::ClipMaskOperation operation, Rml::CompiledGeometryHandle geometry, Rml::Vector2f translation) [override]
Definition at line 163 of file RmlUi_Renderer_GL2.cpp.
References GL_ALWAYS, GL_EQUAL, GL_FALSE, GL_INCR, GL_KEEP, GL_REPLACE, GL_STENCIL_BUFFER_BIT, GL_STENCIL_REF, GL_STENCIL_TEST, GL_TRUE, glClear, glColorMask, glGetIntegerv, glIsEnabled, glStencilFunc, glStencilOp, and RenderGeometry().
SetScissorRegion()
void RenderInterface_GL2::SetScissorRegion (Rml::Rectanglei region) [override]
Definition at line 150 of file RmlUi_Renderer_GL2.cpp.
References glScissor.
SetTransform()
void RenderInterface_GL2::SetTransform (const Rml::Matrix4f * transform) [override]
Definition at line 337 of file RmlUi_Renderer_GL2.cpp.
SetViewport()
void RenderInterface_GL2::SetViewport (int viewport_width, int viewport_height)
Definition at line 54 of file RmlUi_Renderer_GL2.cpp.
Member Data Documentation
TextureEnableWithoutBinding
const Rml::TextureHandle RenderInterface_GL2::TextureEnableWithoutBinding = Rml::TextureHandle(-1) [static]
Definition at line 67 of file RmlUi_Renderer_GL2.h.
Referenced by RenderInterface_GL2_SDL::RenderGeometry(), RenderInterface_GL2_SFML::RenderGeometry(), and RenderGeometry().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_Renderer_GL2.h
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_Renderer_GL2.cpp