C:/Dev/Techstorm-v5/src/application/prototyping/main_march.cpp File Reference
#include <iostream>
#include <string>
#include "generator.hpp"
#include "marching_cubes.hpp"
#include "utilities.hpp"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 8 of file main_march.cpp.
References Generator::read_grid_from_file(), MarchingCubes::triangulate_field(), and write_to_ply().