Techstorm::GameCamera Class Reference
Represents a camera wherein the world is rendered and viewed from.
#include <GameCamera.h>
Public Member Functions
GameCamera ()
virtual ~GameCamera ()
Finalizes an instance of the GameCamera class. Please note that if this is the main camera, it will make the camera with ID 0 the main camera.
void init ()
Initializes this instance.
virtual void update ()
Updates this instance in one of two ways, depending on the camera's settings.
Camera3D getCameraData ()
Gets the camera data.
Vector3 getPosition () const
Gets the position.
Vector3 getTarget () const
Gets the target.
Vector3 getUp () const
Gets up.
float getFovy () const
Gets the camera's fovy (Field of View Y). For more information, please see the section on it in the documentation.
int getProjection () const
Gets the camera's projection.
void setCameraData (Camera3D const &data)
Sets the camera data.
void setPosition (Vector3 position)
Sets the position.
void setTarget (Vector3 target)
Sets the target.
void setUp (Vector3 up)
Sets up.
void setFovy (float fovy)
Sets the fovy.
void setProjection (int projection)
Sets the projection.
void setAsMainCamera ()
Sets this instance as the main camera.
bool isMainCamera () const
Checks if this instance is the main camera.
bool operator== (const GameCamera &other) const =default
Friends
class Renderer
Detailed Description
Represents a camera wherein the world is rendered and viewed from.
Definition at line 10 of file GameCamera.h.
Constructor & Destructor Documentation
GameCamera()
Techstorm::GameCamera::GameCamera () [inline]
Definition at line 12 of file GameCamera.h.
References init().
~GameCamera()
virtual Techstorm::GameCamera::~GameCamera () [inline], [virtual]
Finalizes an instance of the GameCamera class. Please note that if this is the main camera, it will make the camera with ID 0 the main camera.
Definition at line 19 of file GameCamera.h.
References isMainCamera().
Member Function Documentation
getCameraData()
Camera3D Techstorm::GameCamera::getCameraData ()
Gets the camera data.
Returns
A reference to the underlying mCameraData variable
Definition at line 27 of file GameCamera.cpp.
Referenced by Techstorm::Renderer::texture().
getFovy()
float Techstorm::GameCamera::getFovy () const [inline]
Gets the camera's fovy (Field of View Y). For more information, please see the section on it in the documentation.
Returns
The camera's fovy
How Cameras Work
Definition at line 54 of file GameCamera.cpp.
getPosition()
Vector3 Techstorm::GameCamera::getPosition () const [inline]
Gets the position.
Returns
Definition at line 34 of file GameCamera.cpp.
getProjection()
int Techstorm::GameCamera::getProjection () const [inline]
Gets the camera's projection.
Returns
Definition at line 60 of file GameCamera.cpp.
getTarget()
Vector3 Techstorm::GameCamera::getTarget () const [inline]
Gets the target.
Returns
Definition at line 41 of file GameCamera.cpp.
getUp()
Vector3 Techstorm::GameCamera::getUp () const [inline]
Gets up.
Returns
Definition at line 47 of file GameCamera.cpp.
init()
void Techstorm::GameCamera::init ()
Initializes this instance.
Definition at line 3 of file GameCamera.cpp.
References setAsMainCamera().
Referenced by GameCamera().
isMainCamera()
bool Techstorm::GameCamera::isMainCamera () const [inline]
Checks if this instance is the main camera.
Returns
Definition at line 130 of file GameCamera.h.
Referenced by ~GameCamera().
operator==()
bool Techstorm::GameCamera::operator== (const GameCamera & other) const [default]
setAsMainCamera()
void Techstorm::GameCamera::setAsMainCamera () [inline]
Sets this instance as the main camera.
Definition at line 121 of file GameCamera.h.
Referenced by init().
setCameraData()
void Techstorm::GameCamera::setCameraData (Camera3D const & data) [inline]
Sets the camera data.
Parameters
data The data.
Definition at line 66 of file GameCamera.cpp.
setFovy()
void Techstorm::GameCamera::setFovy (float fovy) [inline]
Sets the fovy.
Parameters
fovy The fovy.
Definition at line 90 of file GameCamera.cpp.
setPosition()
void Techstorm::GameCamera::setPosition (Vector3 position) [inline]
Sets the position.
Parameters
position The position.
Definition at line 72 of file GameCamera.cpp.
setProjection()
void Techstorm::GameCamera::setProjection (int projection) [inline]
Sets the projection.
Parameters
projection The projection.
Definition at line 96 of file GameCamera.cpp.
setTarget()
void Techstorm::GameCamera::setTarget (Vector3 target) [inline]
Sets the target.
Parameters
target The target.
Definition at line 78 of file GameCamera.cpp.
setUp()
void Techstorm::GameCamera::setUp (Vector3 up) [inline]
Sets up.
Parameters
up Up.
Definition at line 84 of file GameCamera.cpp.
update()
void Techstorm::GameCamera::update () [virtual]
Updates this instance in one of two ways, depending on the camera's settings.
For a more in-depth explanation of camera settings, see How Cameras Work and GameCamera in the documentation.
Definition at line 4 of file Camera.cpp.
Friends And Related Symbol Documentation
Renderer
friend class Renderer [friend]
Definition at line 146 of file GameCamera.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/renderer/GameCamera.h
C:/Dev/Techstorm-v5/src/engine/renderer/Camera.cpp
C:/Dev/Techstorm-v5/src/engine/renderer/GameCamera.cpp