MarchingCubes Class Reference
#include <marching_cubes.hpp>
Public Member Functions
int calculate_cube_index (GridCell &cell, float isovalue)
Point interpolate (Point &v1, float val1, Point &v2, float val2, float isovalue)
Find the point between v1 and v2 where the functional value = isovalue
std::vector< Point > get_intersection_coordinates (GridCell &cell, float isovalue)
std::vector< std::vector< Point > > get_triangles (std::vector< Point > &intersections, int cubeIndex)
Given cubeIndex, get the edge table entry and using intersections, make all triangles.
void print_triangles (std::vector< std::vector< Point > > triangles)
Utility function to print a triangle.
std::vector< std::vector< Point > > triangulate_cell (GridCell &cell, float isovalue)
Get triangles of a single cell.
std::vector< std::vector< Point > > triangulate_field (std::vector< std::vector< std::vector< float > > > &scalarFunction, float isovalue)
Triangulate a scalar field represented by scalarFunction. isovalue should be used for isovalue computation.
Public Attributes
std::vector< std::pair< int, int > > edgeToVertices
edgeToVertices[i] = {a, b} => edge i joins vertices a and b
const int edgeTable [256]
const int triangleTable [256][16]
triangleTable[i] is a list of edges forming triangles for cubeIndex i
Detailed Description
Definition at line 13 of file marching_cubes.hpp.
Member Function Documentation
calculate_cube_index()
int MarchingCubes::calculate_cube_index (GridCell & cell, float isovalue)
Given a cell, calculate its cube index The cube index is an 8-bit encoding. Each bit represents a vertex. index[i] is the ith bit If the value at the ith vertex is < isovalue, index[i] = 1. Else, index[i] = 0
Definition at line 9 of file marching_cubes.cpp.
References GridCell::value.
Referenced by get_intersection_coordinates(), and triangulate_cell().
get_intersection_coordinates()
std::vector< Point > MarchingCubes::get_intersection_coordinates (GridCell & cell, float isovalue)
Returns all intersection coordinates of a cell with the isosurface (Calls interpolate())
Definition at line 17 of file marching_cubes.cpp.
References calculate_cube_index(), edgeTable, edgeToVertices, interpolate(), GridCell::value, and GridCell::vertex.
Referenced by triangulate_cell().
get_triangles()
std::vector< std::vector< Point > > MarchingCubes::get_triangles (std::vector< Point > & intersections, int cubeIndex)
Given cubeIndex, get the edge table entry and using intersections, make all triangles.
Definition at line 54 of file marching_cubes.cpp.
References triangleTable.
Referenced by triangulate_cell().
interpolate()
Point MarchingCubes::interpolate (Point & v1, float val1, Point & v2, float val2, float isovalue)
Find the point between v1 and v2 where the functional value = isovalue
Definition at line 42 of file marching_cubes.cpp.
References Point::x, Point::y, and Point::z.
Referenced by get_intersection_coordinates().
print_triangles()
void MarchingCubes::print_triangles (std::vector< std::vector< Point > > triangles)
Utility function to print a triangle.
Definition at line 68 of file marching_cubes.cpp.
triangulate_cell()
std::vector< std::vector< Point > > MarchingCubes::triangulate_cell (GridCell & cell, float isovalue)
Get triangles of a single cell.
Definition at line 78 of file marching_cubes.cpp.
References calculate_cube_index(), get_intersection_coordinates(), and get_triangles().
Referenced by triangulate_field().
triangulate_field()
std::vector< std::vector< Point > > MarchingCubes::triangulate_field (std::vector< std::vector< std::vector< float > > > & scalarFunction, float isovalue)
Triangulate a scalar field represented by scalarFunction. isovalue should be used for isovalue computation.
Definition at line 102 of file marching_cubes.cpp.
References triangulate_cell().
Referenced by main().
Member Data Documentation
edgeTable
const int MarchingCubes::edgeTable[256]
edgeTable[i] is a 12 bit number; i is a cubeIndex edgeTable[i][j] = 1 if isosurface intersects edge j for cubeIndex i
Definition at line 27 of file marching_cubes.hpp.
Referenced by get_intersection_coordinates().
edgeToVertices
std::vector<std::pair<int, int> > MarchingCubes::edgeToVertices
Initial value:
=
        {
            {0, 1}, {1, 2}, {2, 3}, {0, 3},
            {4, 5}, {5, 6}, {6, 7}, {4, 7},
            {0, 4}, {1, 5}, {2, 6}, {3, 7}
        }
edgeToVertices[i] = {a, b} => edge i joins vertices a and b
Definition at line 18 of file marching_cubes.hpp.
Referenced by get_intersection_coordinates().
triangleTable
const int MarchingCubes::triangleTable[256][16]
triangleTable[i] is a list of edges forming triangles for cubeIndex i
Definition at line 64 of file marching_cubes.hpp.
Referenced by get_triangles().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/prototyping/marching_cubes.hpp
C:/Dev/Techstorm-v5/src/application/prototyping/marching_cubes.cpp