C:/Dev/Techstorm-v5/src/application/prototyping/utilities.cpp File Reference
#include "utilities.hpp"
Functions
VertexContainer hash_vertices_to_indices (std::vector< std::vector< Point > > &triangles)
void write_to_ply (std::vector< std::vector< Point > > &triangles, const char *path)
void write_triangles_to_file (std::vector< std::vector< Point > > triangles, const char *path)
Function Documentation
hash_vertices_to_indices()
VertexContainer hash_vertices_to_indices (std::vector< std::vector< Point > > & triangles)
Definition at line 3 of file utilities.cpp.
References VertexContainer::triangles, and VertexContainer::vertexMap.
Referenced by write_to_ply().
write_to_ply()
void write_to_ply (std::vector< std::vector< Point > > & triangles, const char * path)
Definition at line 25 of file utilities.cpp.
References hash_vertices_to_indices(), VertexContainer::triangles, and VertexContainer::vertexMap.
Referenced by main().
write_triangles_to_file()
void write_triangles_to_file (std::vector< std::vector< Point > > triangles, const char * path)
Definition at line 57 of file utilities.cpp.