RenderInterface_VK Class Reference
#include <RmlUi_Renderer_VK.h>
Public Types
using CreateSurfaceCallback = bool(*)(VkInstance instance, VkSurfaceKHR *out_surface)
Public Member Functions
RenderInterface_VK ()
~RenderInterface_VK ()
bool Initialize (Rml::Vector< const char * > required_extensions, CreateSurfaceCallback create_surface_callback)
void Shutdown ()
void BeginFrame ()
void EndFrame ()
void SetViewport (int width, int height)
bool IsSwapchainValid ()
void RecreateSwapchain ()
Rml::CompiledGeometryHandle CompileGeometry (Rml::Span< const Rml::Vertex > vertices, Rml::Span< const int > indices) override
Called by RmlUi when it wants to compile geometry it believes will be static for the forseeable future.
void RenderGeometry (Rml::CompiledGeometryHandle handle, Rml::Vector2f translation, Rml::TextureHandle texture) override
Called by RmlUi when it wants to render application-compiled geometry.
void ReleaseGeometry (Rml::CompiledGeometryHandle geometry) override
Called by RmlUi when it wants to release application-compiled geometry.
Rml::TextureHandle LoadTexture (Rml::Vector2i &texture_dimensions, const Rml::String &source) override
Called by RmlUi when a texture is required by the library.
Rml::TextureHandle GenerateTexture (Rml::Span< const Rml::byte > source_data, Rml::Vector2i source_dimensions) override
Called by RmlUi when a texture is required to be built from an internally-generated sequence of pixels.
void ReleaseTexture (Rml::TextureHandle texture_handle) override
Called by RmlUi when a loaded texture is no longer required.
void EnableScissorRegion (bool enable) override
Called by RmlUi when it wants to enable or disable scissoring to clip content.
void SetScissorRegion (Rml::Rectanglei region) override
Called by RmlUi when it wants to change the scissor region.
void SetTransform (const Rml::Matrix4f *transform) override
Called by RmlUi when it wants to set the current transform matrix to a new matrix.
Static Public Attributes
static constexpr uint32_t kSwapchainBackBufferCount = 3
static constexpr VkDeviceSize kVideoMemoryForAllocation = 4 * 1024 * 1024
Detailed Description
Vulkan render interface for RmlUi
My aim is to create compact, but easy to use class I understand that it isn't good architectural choice to keep all things in one class But I follow to RMLUI design and for implementing one GAPI backend it just needs one class For user looks cool, but for programmer...
It's better to try operate with very clean 'one-class' architecture rather than create own library for Vulkan With many different classes, with not trivial signatures and etc And as a result we should document that library so it's just a headache for all of us
Reminder to users: If you want to implement your Vulkan renderer check previous commits of this work, because current system works only with new and delete operations every frame (CPU side), on GPU we implemented the pre-allocated buffer with virtual allocs (Vma) so there's no problems and all fine. I wrote all ideas and implementation for that.
Author
wh1t3lord (https://github.com/wh1t3lord)
Definition at line 72 of file RmlUi_Renderer_VK.h.
Member Typedef Documentation
CreateSurfaceCallback
using RenderInterface_VK::CreateSurfaceCallback = bool (*)(VkInstance instance, VkSurfaceKHR* out_surface)
Definition at line 80 of file RmlUi_Renderer_VK.h.
Constructor & Destructor Documentation
RenderInterface_VK()
RenderInterface_VK::RenderInterface_VK ()
Definition at line 88 of file RmlUi_Renderer_VK.cpp.
~RenderInterface_VK()
RenderInterface_VK::~RenderInterface_VK ()
Definition at line 103 of file RmlUi_Renderer_VK.cpp.
Member Function Documentation
BeginFrame()
void RenderInterface_VK::BeginFrame ()
Definition at line 687 of file RmlUi_Renderer_VK.cpp.
References VkRenderPassBeginInfo::clearValueCount, VkClearValue::color, VkClearValue::depthStencil, VkRect2D::extent, VkCommandBufferBeginInfo::flags, VkRenderPassBeginInfo::framebuffer, VkExtent2D::height, VkRect2D::offset, VkRenderPassBeginInfo::pClearValues, VkCommandBufferBeginInfo::pInheritanceInfo, VkCommandBufferBeginInfo::pNext, VkRenderPassBeginInfo::pNext, VkRenderPassBeginInfo::renderArea, VkRenderPassBeginInfo::renderPass, RMLUI_VK_ASSERTMSG, VkCommandBufferBeginInfo::sType, VkRenderPassBeginInfo::sType, VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO, VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO, vkBeginCommandBuffer, vkCmdBeginRenderPass, vkCmdSetViewport, VkExtent2D::width, VkOffset2D::x, and VkOffset2D::y.
CompileGeometry()
Rml::CompiledGeometryHandle RenderInterface_VK::CompileGeometry (Rml::Span< const Rml::Vertex > vertices, Rml::Span< const int > indices) [override]
Called by RmlUi when it wants to compile geometry it believes will be static for the forseeable future.
Definition at line 105 of file RmlUi_Renderer_VK.cpp.
References RMLUI_VK_ASSERTMSG.
Referenced by SetScissorRegion().
EnableScissorRegion()
void RenderInterface_VK::EnableScissorRegion (bool enable) [override]
Called by RmlUi when it wants to enable or disable scissoring to clip content.
Definition at line 289 of file RmlUi_Renderer_VK.cpp.
References vkCmdSetScissor.
EndFrame()
void RenderInterface_VK::EndFrame ()
Definition at line 735 of file RmlUi_Renderer_VK.cpp.
References RMLUI_VK_ASSERTMSG, vkCmdEndRenderPass, and vkEndCommandBuffer.
GenerateTexture()
Rml::TextureHandle RenderInterface_VK::GenerateTexture (Rml::Span< const Rml::byte > source_data, Rml::Vector2i source_dimensions) [override]
Called by RmlUi when a texture is required to be built from an internally-generated sequence of pixels.
Definition at line 486 of file RmlUi_Renderer_VK.cpp.
Referenced by LoadTexture().
Initialize()
bool RenderInterface_VK::Initialize (Rml::Vector< const char * > required_extensions, CreateSurfaceCallback create_surface_callback)
Definition at line 798 of file RmlUi_Renderer_VK.cpp.
References gladLoaderLoadVulkan(), RMLUI_VK_ASSERTMSG, and VK_NULL_HANDLE.
IsSwapchainValid()
bool RenderInterface_VK::IsSwapchainValid ()
Definition at line 788 of file RmlUi_Renderer_VK.cpp.
LoadTexture()
Rml::TextureHandle RenderInterface_VK::LoadTexture (Rml::Vector2i & texture_dimensions, const Rml::String & source) [override]
Called by RmlUi when a texture is required by the library.
Definition at line 407 of file RmlUi_Renderer_VK.cpp.
References TGAHeader::bitsPerPixel, TGAHeader::dataType, GenerateTexture(), TGAHeader::height, TGAHeader::imageDescriptor, and TGAHeader::width.
RecreateSwapchain()
void RenderInterface_VK::RecreateSwapchain ()
Definition at line 793 of file RmlUi_Renderer_VK.cpp.
References SetViewport().
ReleaseGeometry()
void RenderInterface_VK::ReleaseGeometry (Rml::CompiledGeometryHandle geometry) [override]
Called by RmlUi when it wants to release application-compiled geometry.
Definition at line 280 of file RmlUi_Renderer_VK.cpp.
Referenced by SetScissorRegion().
ReleaseTexture()
void RenderInterface_VK::ReleaseTexture (Rml::TextureHandle texture_handle) [override]
Called by RmlUi when a loaded texture is no longer required.
Definition at line 671 of file RmlUi_Renderer_VK.cpp.
RenderGeometry()
void RenderInterface_VK::RenderGeometry (Rml::CompiledGeometryHandle handle, Rml::Vector2f translation, Rml::TextureHandle texture) [override]
Called by RmlUi when it wants to render application-compiled geometry.
Definition at line 138 of file RmlUi_Renderer_VK.cpp.
References VkWriteDescriptorSet::descriptorCount, VkWriteDescriptorSet::descriptorType, VkWriteDescriptorSet::dstBinding, VkWriteDescriptorSet::dstSet, VkDescriptorImageInfo::imageLayout, VkDescriptorImageInfo::imageView, VkWriteDescriptorSet::pImageInfo, RMLUI_VK_ASSERTMSG, VkDescriptorImageInfo::sampler, VkWriteDescriptorSet::sType, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_INDEX_TYPE_UINT32, VK_PIPELINE_BIND_POINT_GRAPHICS, VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, vkCmdBindDescriptorSets, vkCmdBindIndexBuffer, vkCmdBindPipeline, vkCmdBindVertexBuffers, vkCmdDrawIndexed, and vkUpdateDescriptorSets.
Referenced by SetScissorRegion().
SetScissorRegion()
void RenderInterface_VK::SetScissorRegion (Rml::Rectanglei region) [override]
Called by RmlUi when it wants to change the scissor region.
Definition at line 308 of file RmlUi_Renderer_VK.cpp.
References VkClearAttachment::aspectMask, VkClearAttachment::clearValue, VkClearAttachment::colorAttachment, CompileGeometry(), VkClearDepthStencilValue::depth, VkClearValue::depthStencil, VkRect2D::extent, VkExtent2D::height, VkClearRect::layerCount, VkRect2D::offset, VkClearRect::rect, ReleaseGeometry(), RenderGeometry(), VkDebugUtilsLabelEXT::sType, VK_IMAGE_ASPECT_DEPTH_BIT, VK_IMAGE_ASPECT_STENCIL_BIT, VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT, vkCmdClearAttachments, vkCmdInsertDebugUtilsLabelEXT, vkCmdSetScissor, VkExtent2D::width, VkOffset2D::x, and VkOffset2D::y.
SetTransform()
void RenderInterface_VK::SetTransform (const Rml::Matrix4f * transform) [override]
Called by RmlUi when it wants to set the current transform matrix to a new matrix.
Definition at line 681 of file RmlUi_Renderer_VK.cpp.
SetViewport()
void RenderInterface_VK::SetViewport (int width, int height)
Definition at line 752 of file RmlUi_Renderer_VK.cpp.
References VkExtent2D::height, RMLUI_VK_ASSERTMSG, vkDeviceWaitIdle, and VkExtent2D::width.
Referenced by RecreateSwapchain().
Shutdown()
void RenderInterface_VK::Shutdown ()
Definition at line 829 of file RmlUi_Renderer_VK.cpp.
References gladLoaderUnloadVulkan(), RMLUI_VK_ASSERTMSG, and vkDeviceWaitIdle.
Member Data Documentation
kSwapchainBackBufferCount
constexpr uint32_t RenderInterface_VK::kSwapchainBackBufferCount = 3 [static], [constexpr]
Definition at line 74 of file RmlUi_Renderer_VK.h.
kVideoMemoryForAllocation
constexpr VkDeviceSize RenderInterface_VK::kVideoMemoryForAllocation = 4 * 1024 * 1024 [static], [constexpr]
Definition at line 75 of file RmlUi_Renderer_VK.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_Renderer_VK.h
C:/Dev/Techstorm-v5/src/engine/backends/RmlUi_Renderer_VK.cpp