Techstorm::Renderer Class Reference
Serves as the renderer for the game.
#include <Renderer.h>
Public Member Functions
Renderer ()
Initializes a new instance of the Renderer class.
void initialize ()
Initializes this instance.
void render (GameCamera &cam)
Renders the render texture to the screen using the specified camera.
void texture (GameCamera &cam)
Textures the scene to the render texture using the specified camera.
void update ()
void drawFBO ()
Draws the FBO/RenderTexture2D.
void addGameObject (GameObject *gameObject)
Adds the game object.
void removeGameObject (GameObject *gameObject)
Removes a game object.
void addGameObjectGate (IGameObjectGate *gameObjectGate)
Adds a game object gate.
void removeGameObjectGate (IGameObjectGate *gameObjectGate)
Removes a game object gate.
void cleanup ()
Cleanups this instance.
Public Attributes
GameCamera mCamera
Detailed Description
Serves as the renderer for the game.
Definition at line 21 of file Renderer.h.
Constructor & Destructor Documentation
Renderer()
Techstorm::Renderer::Renderer () [inline]
Initializes a new instance of the Renderer class.
Definition at line 27 of file Renderer.h.
References mCamera, Techstorm::GameCamera::setFovy(), Techstorm::GameCamera::setPosition(), Techstorm::GameCamera::setProjection(), Techstorm::GameCamera::setTarget(), and Techstorm::GameCamera::setUp().
Member Function Documentation
addGameObject()
void Techstorm::Renderer::addGameObject (GameObject * gameObject)
Adds the game object.
Parameters
gameObject The game object pointer to add.
Definition at line 71 of file Renderer.cpp.
addGameObjectGate()
void Techstorm::Renderer::addGameObjectGate (IGameObjectGate * gameObjectGate)
Adds a game object gate.
Parameters
gameObjectGate The game object gate pointer to add.
See also
IGameObjectGate
Definition at line 81 of file Renderer.cpp.
cleanup()
void Techstorm::Renderer::cleanup ()
Cleanups this instance.
Definition at line 85 of file Renderer.cpp.
drawFBO()
void Techstorm::Renderer::drawFBO ()
Draws the FBO/RenderTexture2D.
Definition at line 65 of file Renderer.cpp.
initialize()
void Techstorm::Renderer::initialize ()
Initializes this instance.
Definition at line 25 of file Renderer.cpp.
removeGameObject()
void Techstorm::Renderer::removeGameObject (GameObject * gameObject)
Removes a game object.
Parameters
gameObject The game object pointer to remove.
Definition at line 76 of file Renderer.cpp.
removeGameObjectGate()
void Techstorm::Renderer::removeGameObjectGate (IGameObjectGate * gameObjectGate)
Removes a game object gate.
Parameters
gameObjectGate The game object gate pointer to remove.
See also
IGameObjectGate
Definition at line 83 of file Renderer.cpp.
render()
void Techstorm::Renderer::render (GameCamera & cam)
Renders the render texture to the screen using the specified camera.
Parameters
cam The cam.
Definition at line 33 of file Renderer.cpp.
texture()
void Techstorm::Renderer::texture (GameCamera & cam)
Textures the scene to the render texture using the specified camera.
Parameters
cam The cam.
Definition at line 42 of file Renderer.cpp.
References Techstorm::GameCamera::getCameraData().
update()
void Techstorm::Renderer::update ()
Definition at line 60 of file Renderer.cpp.
Member Data Documentation
mCamera
GameCamera Techstorm::Renderer::mCamera
Definition at line 91 of file Renderer.h.
Referenced by Renderer().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/renderer/Renderer.h
C:/Dev/Techstorm-v5/src/engine/renderer/Renderer.cpp